import type { CustomerIndustryTemplate } from '../customerTemplate.types'

/**
 * 체육관·헬스 CRM 고객 템플릿 정적 정의(v0.1).
 *
 * - 이 파일은 **선언(JSON-like) 레이어만** 담당한다. CustomersPage·tenant.config·DB 스키마와 **연결되어 있지 않다**.
 * - 수퍼관리 Preview는 `PLATFORM_ADMIN_STATIC_CUSTOMER_TEMPLATES` + `buildCustomerTemplatePreviewViewModel` 로만 접근된다.
 *
 * 폼 필드 호환키:
 * - `gym.fitnessGoal`: 요청·UI 호환용 키이다. Field Registry 검증에서는 canonical `gym.workoutGoal` 로 alias 해석된다
 *   (`CUSTOMER_FIELD_KEY_ALIAS_TO_CANONICAL`).
 *
 * 목록 컬럼 키:
 * - 카탈로그 `programName`·`paymentStatus` 는 각각 gov(`gov.programName`)·계약(`contract.paymentStatus`) 계열과 **고정(SSOT)** 이다.
 * - 체육관 프로그램명·결제 상태는 다른 sourceField 이므로 `gymProgramName`·`gymPaymentStatus` 를 쓴다.
 */
export const gymCustomerTemplateV01: CustomerIndustryTemplate = {
  meta: {
    templateId: 'gym_customer_v1',
    industryCode: 'gym',
    version: '0.1.0',
    schemaVersion: 'customer-template.v1',
  },
  sharedFeatureBindings: Object.freeze([
    'crm-storage-files',
    'crm-consultations',
    'crm-inline-notes',
    'notifications-sms-gateway',
    'documents-send',
    'permissions-scope',
  ]),
  extensionFeatureBindings: Object.freeze([
    'workout-automation',
    'membership-expiry-alert',
    'gym-attendance-tracking',
    'gym-reservation-management',
    'gym-session-package',
    'gym-renewal-followup',
    'gym-trainer-assignment',
  ]),
  formFields: Object.freeze([
    {
      fieldKey: 'customer.name',
      label: '이름',
      widget: 'text',
      required: true,
      visibleDefault: true,
      order: 100,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'customer.phone',
      label: '연락처',
      widget: 'phone',
      required: true,
      visibleDefault: true,
      order: 110,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'customer.birthDate',
      label: '생년월일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 120,
      privacyLevel: 'sensitive',
      domain: 'gym',
    },
    {
      fieldKey: 'customer.gender',
      label: '성별',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 130,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'customer.address',
      label: '주소',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 140,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'customer.memo',
      label: '메모',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 150,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.memberCode',
      label: '회원번호',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 200,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.membershipType',
      label: '회원권 유형',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 210,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.programName',
      label: '프로그램명',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 220,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.membershipStartDate',
      label: '회원권 시작일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 230,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.membershipEndDate',
      label: '회원권 만료일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 240,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.remainingSessions',
      label: '잔여 횟수',
      widget: 'number',
      required: false,
      visibleDefault: true,
      order: 250,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.trainerName',
      label: '담당 트레이너',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 260,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.fitnessGoal',
      label: '운동 목표',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 270,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.healthNotes',
      label: '건강 메모',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 280,
      privacyLevel: 'sensitive',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.attendanceStatus',
      label: '출석 상태',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 290,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.lastVisitDate',
      label: '마지막 방문일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 300,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.nextReservationDate',
      label: '다음 예약일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 310,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.paymentStatus',
      label: '결제 상태',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 320,
      privacyLevel: 'normal',
      domain: 'gym',
    },
    {
      fieldKey: 'gym.renewalStatus',
      label: '재등록 상태',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 330,
      privacyLevel: 'normal',
      domain: 'gym',
    },
  ]),
  listColumns: Object.freeze([
    {
      columnKey: 'name',
      label: '이름',
      order: 10,
      visibleDefault: true,
      domain: 'gym',
    },
    {
      columnKey: 'phone',
      label: '연락처',
      order: 20,
      visibleDefault: true,
      domain: 'gym',
    },
    {
      columnKey: 'membershipType',
      label: '회원권 유형',
      order: 30,
      visibleDefault: true,
      domain: 'gym',
    },
    {
      columnKey: 'gymProgramName',
      label: '프로그램명',
      order: 40,
      visibleDefault: true,
      domain: 'gym',
    },
    {
      columnKey: 'membershipEndDate',
      label: '회원권 만료일',
      order: 50,
      visibleDefault: true,
      domain: 'gym',
    },
    {
      columnKey: 'remainingSessions',
      label: '잔여 횟수',
      order: 60,
      visibleDefault: true,
      domain: 'gym',
    },
    {
      columnKey: 'trainerName',
      label: '담당 트레이너',
      order: 70,
      visibleDefault: true,
      domain: 'gym',
    },
    {
      columnKey: 'lastVisitDate',
      label: '마지막 방문일',
      order: 80,
      visibleDefault: true,
      domain: 'gym',
    },
    {
      columnKey: 'nextReservationDate',
      label: '다음 예약일',
      order: 90,
      visibleDefault: true,
      domain: 'gym',
    },
    {
      columnKey: 'gymPaymentStatus',
      label: '결제 상태',
      order: 100,
      visibleDefault: true,
      domain: 'gym',
    },
    {
      columnKey: 'renewalStatus',
      label: '재등록 상태',
      order: 110,
      visibleDefault: true,
      domain: 'gym',
    },
    {
      columnKey: 'memoSummary',
      label: '메모 요약',
      order: 120,
      visibleDefault: true,
      domain: 'gym',
    },
  ]),
  detailTabs: Object.freeze([
    {
      tabId: 'basic-info',
      label: '기본 정보',
      featureBinding: 'gym-section-basic-info',
      order: 10,
      domain: 'gym',
      visibleDefault: true,
    },
    {
      tabId: 'membership-program',
      label: '회원권 / 프로그램 정보',
      featureBinding: 'gym-section-membership-program',
      order: 20,
      domain: 'gym',
      visibleDefault: true,
    },
    {
      tabId: 'fitness-health',
      label: '운동 목표 / 건강 메모',
      featureBinding: 'gym-section-fitness-health',
      order: 30,
      domain: 'gym',
      visibleDefault: true,
    },
    {
      tabId: 'attendance-reservations',
      label: '출석 / 예약 이력',
      featureBinding: 'gym-section-attendance-reservations',
      order: 40,
      domain: 'gym',
      visibleDefault: true,
    },
    {
      tabId: 'consultations',
      label: '상담 이력',
      featureBinding: 'crm-consultations',
      order: 50,
      domain: 'gym',
      visibleDefault: true,
    },
    {
      tabId: 'files',
      label: '파일 / 첨부자료',
      featureBinding: 'crm-storage-files',
      order: 60,
      domain: 'gym',
      visibleDefault: true,
    },
    {
      tabId: 'payment-renewal',
      label: '결제 / 재등록 관리',
      featureBinding: 'gym-section-payment-renewal',
      order: 70,
      domain: 'gym',
      visibleDefault: true,
    },
    {
      tabId: 'notes',
      label: '메모',
      featureBinding: 'crm-inline-notes',
      order: 80,
      domain: 'gym',
      visibleDefault: true,
    },
  ]),
}
