import type { CustomerIndustryTemplate } from '../customerTemplate.types'

/**
 * insurance customer template v0.1 — 현 행 코드베이스(보험 고객관리) 초기 역추출.
 * CustomersPage 에 아직 연결하지 않는다.
 */
export const insuranceCustomerTemplateV01: CustomerIndustryTemplate = {
  meta: {
    templateId: 'insurance_customer_v1',
    industryCode: 'insurance',
    version: '0.1',
    schemaVersion: '0.1',
  },
  sharedFeatureBindings: Object.freeze([
    'crm-storage-files',
    'crm-consultations',
    'crm-inline-notes',
    'crm-linked-customers',
    'notifications-sms-gateway',
    'esign-send',
    'esign-history',
  ]),
  extensionFeatureBindings: Object.freeze([
    'insurance-ga-excel',
    'insurance-auto-form',
    'insurance-claim-requests',
    'insurance-cars',
    'insurance-forms',
  ]),
  formFields: Object.freeze([
    {
      fieldKey: 'name',
      label: '이름',
      widget: 'text',
      required: true,
      visibleDefault: true,
      order: 10,
      privacyLevel: 'normal',
      domain: 'core',
    },
    {
      fieldKey: 'phone',
      label: '연락처',
      widget: 'phone',
      required: true,
      visibleDefault: true,
      order: 20,
      privacyLevel: 'normal',
      domain: 'core',
    },
    {
      fieldKey: 'ssn',
      label: '주민등록번호',
      widget: 'ssn',
      required: false,
      visibleDefault: true,
      order: 30,
      privacyLevel: 'identifying',
      domain: 'insurance',
    },
    {
      fieldKey: 'birthDate',
      label: '생년월일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 35,
      privacyLevel: 'sensitive',
      domain: 'core',
    },
    {
      fieldKey: 'gender',
      label: '성별',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 40,
      privacyLevel: 'normal',
      domain: 'core',
    },
    {
      fieldKey: 'address',
      label: '주소',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 50,
      privacyLevel: 'normal',
      domain: 'core',
    },
    {
      fieldKey: 'job',
      label: '직업·회사',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 60,
      privacyLevel: 'normal',
      domain: 'core',
    },
    {
      fieldKey: 'height',
      label: '키',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 70,
      privacyLevel: 'sensitive',
      domain: 'core',
    },
    {
      fieldKey: 'weight',
      label: '몸무게',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 80,
      privacyLevel: 'sensitive',
      domain: 'core',
    },
    {
      fieldKey: 'medical',
      label: '의료·건강 고지',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 90,
      privacyLevel: 'sensitive',
      domain: 'insurance',
    },
    {
      fieldKey: 'driving',
      label: '운전(텍스트)',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 100,
      privacyLevel: 'normal',
      domain: 'insurance',
    },
    {
      fieldKey: 'isDriver',
      label: '운전 여부',
      widget: 'boolean',
      required: false,
      visibleDefault: true,
      order: 110,
      privacyLevel: 'normal',
      domain: 'insurance',
    },
    {
      fieldKey: 'carType',
      label: '차종',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 120,
      privacyLevel: 'normal',
      domain: 'insurance',
    },
    {
      fieldKey: 'carNumber',
      label: '차량번호',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 130,
      privacyLevel: 'normal',
      domain: 'insurance',
    },
    {
      fieldKey: 'carModel',
      label: '차량 모델',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 140,
      privacyLevel: 'normal',
      domain: 'insurance',
    },
    {
      fieldKey: 'carYear',
      label: '차량 연식',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 150,
      privacyLevel: 'normal',
      domain: 'insurance',
    },
    {
      fieldKey: 'renewalDate',
      label: '만기·갱신 예정일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 160,
      privacyLevel: 'normal',
      domain: 'insurance',
    },
    {
      fieldKey: 'insuranceAge',
      label: '보험나이',
      widget: 'number',
      required: false,
      visibleDefault: true,
      order: 170,
      privacyLevel: 'normal',
      domain: 'insurance',
    },
    {
      fieldKey: 'nextAgeDate',
      label: '상령일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 180,
      privacyLevel: 'normal',
      domain: 'insurance',
    },
    {
      fieldKey: 'isFavorite',
      label: '중요 고객',
      widget: 'boolean',
      required: false,
      visibleDefault: true,
      order: 190,
      privacyLevel: 'normal',
      domain: 'core',
    },
    {
      fieldKey: 'customerCode',
      label: '고객번호',
      widget: 'readonly-text',
      required: false,
      visibleDefault: true,
      order: 200,
      privacyLevel: 'normal',
      domain: 'core',
    },
  ]),
  listColumns: Object.freeze([
    {
      columnKey: 'name',
      label: '이름',
      order: 10,
      visibleDefault: true,
      domain: 'core',
    },
    {
      columnKey: 'phone',
      label: '연락처',
      order: 20,
      visibleDefault: true,
      domain: 'core',
    },
    {
      columnKey: 'isFavorite',
      label: '즐겨찾기',
      order: 30,
      visibleDefault: true,
      domain: 'core',
    },
    {
      columnKey: 'ssnMasked',
      label: '주민등록번호(표시)',
      order: 40,
      visibleDefault: true,
      domain: 'insurance',
    },
    {
      columnKey: 'carNumber',
      label: '차량번호',
      order: 50,
      visibleDefault: true,
      domain: 'insurance',
    },
    {
      columnKey: 'renewalDate',
      label: '만기일',
      order: 60,
      visibleDefault: true,
      domain: 'insurance',
    },
    {
      columnKey: 'lastConsultDate',
      label: '최근 상담일',
      order: 70,
      visibleDefault: true,
      domain: 'core',
    },
    {
      columnKey: 'memoSummary',
      label: '메모 요약',
      order: 80,
      visibleDefault: true,
      domain: 'core',
    },
  ]),
  detailTabs: Object.freeze([
    {
      tabId: 'files',
      label: '파일',
      featureBinding: 'crm-storage-files',
      order: 10,
      domain: 'core',
      visibleDefault: true,
    },
    {
      tabId: 'consultations',
      label: '상담',
      featureBinding: 'crm-consultations',
      order: 20,
      domain: 'core',
      visibleDefault: true,
    },
    {
      tabId: 'ga-excel',
      label: 'GA 데이터',
      featureBinding: 'insurance-ga-excel',
      order: 30,
      domain: 'insurance',
      visibleDefault: true,
    },
    {
      tabId: 'memos',
      label: '메모',
      featureBinding: 'crm-inline-notes',
      order: 40,
      domain: 'core',
      visibleDefault: true,
    },
    {
      tabId: 'auto-form',
      label: '자동차 신청',
      featureBinding: 'insurance-auto-form',
      order: 50,
      domain: 'insurance',
      visibleDefault: true,
    },
    {
      tabId: 'claim-requests',
      label: '청구 요청',
      featureBinding: 'insurance-claim-requests',
      order: 60,
      domain: 'insurance',
      visibleDefault: true,
    },
  ]),
}
