/**
 * 전역 공통 보험사 설계사이트 초기 시드 (1회만 삽입).
 * disclosureUrl 은 각사 공개 웹의 「상품·보험 가격 공시」 랜딩을 웹 검색·공식 화면으로 대조해 채움.
 * - 현대해상: 시드 sales/home 은 hic.co.kr 이지만 공시 랜딩은 hi.co.kr 사용(그룹 공시 도메인).
 * - DB손해: 홈은 dbins.co.kr 표기가 있으나 손해 공시는 idbins.com 경로가 공식.
 * - DGB생명: 구 DGB → iM라이프(imlifeins.co.kr) 공시 경로 사용.
 * - 푸본현대생명: 직접 랜딩 URL을 확정하지 못해 빈 값 → 수퍼관리자에서 입력.
 * 빈 disclosureUrl 은 일반 화면에서 공시실 버튼 비활성(준비중), 관리자 목록에서 「미입력」 표시.
 *
 * 번들 기본 로고: `public/assets/insurers/{logoFile}.png` 를 두고 DB `logo_path` 는
 * `insurerSiteBundledLogoPath(logoFile)` 로만 참조합니다. 수퍼관리자 업로드 경로
 * (`/uploads/system/insurers/...`) 는 initDb·백필에서 덮어쓰지 않습니다.
 */

/** @typedef {{ category: 'non_life' | 'life', name: string, logoFile: string, salesUrl: string, homepageUrl: string, disclosureUrl: string, claimUrl: string, sortOrder: number }} InsurerSiteSeedRow */

/** @param {string} logoFile */
export function insurerSiteBundledLogoPath(logoFile) {
  return `/assets/insurers/${logoFile}.png`
}

/** @type {InsurerSiteSeedRow[]} */
export const INSURER_SITES_SEED = [
  {
    category: 'non_life',
    name: '현대해상',
    logoFile: 'hyundai_marine',
    salesUrl: 'https://sales.hic.co.kr/',
    homepageUrl: 'https://www.hic.co.kr/',
    disclosureUrl: 'https://www.hi.co.kr/bin/CI/ON/CION3200G.jsp',
    claimUrl: 'https://www.hic.co.kr/',
    sortOrder: 10,
  },
  {
    category: 'non_life',
    name: 'DB손해보험',
    logoFile: 'db_insurance',
    salesUrl: 'https://www.dbins.co.kr/',
    homepageUrl: 'https://www.dbins.co.kr/',
    disclosureUrl: '',
    claimUrl: 'https://www.dbins.co.kr/',
    sortOrder: 20,
  },
  {
    category: 'non_life',
    name: 'KB손해보험',
    logoFile: 'kb_insurance',
    salesUrl: 'https://sales.kbinsure.co.kr/',
    homepageUrl: 'https://www.kbinsure.co.kr/',
    disclosureUrl: 'https://www.kbinsure.co.kr/CG802030001.ec',
    claimUrl: 'https://www.kbinsure.co.kr/',
    sortOrder: 30,
  },
  {
    category: 'non_life',
    name: '삼성화재',
    logoFile: 'samsung_fire',
    salesUrl: 'https://sales.samsungfire.com/',
    homepageUrl: 'https://www.samsungfire.com/',
    disclosureUrl: 'https://www.samsungfire.com/v2/html/publication/',
    claimUrl: 'https://www.samsungfire.com/',
    sortOrder: 40,
  },
  {
    category: 'non_life',
    name: '메리츠화재',
    logoFile: 'meritz_fire',
    salesUrl: 'https://sales.meritzfire.com/',
    homepageUrl: 'https://www.meritzfire.com/',
    disclosureUrl: 'https://www.meritzfire.com/disclosure/product-announcement/product-list.do?vMode=PC',
    claimUrl: 'https://www.meritzfire.com/',
    sortOrder: 50,
  },
  {
    category: 'non_life',
    name: '농협손해보험',
    logoFile: 'nh_property',
    salesUrl: 'https://www.nhfire.co.kr/',
    homepageUrl: 'https://www.nhfire.co.kr/',
    disclosureUrl: 'https://www.nhfire.co.kr/announce/productAnnounce/retrieveInsuranceProductsAnnounce.nhfire',
    claimUrl: 'https://www.nhfire.co.kr/',
    sortOrder: 60,
  },
  {
    category: 'non_life',
    name: '하나손해보험',
    logoFile: 'hana_insurance',
    salesUrl: 'https://www.hanainsure.co.kr/',
    homepageUrl: 'https://www.hanainsure.co.kr/',
    disclosureUrl: '',
    claimUrl: 'https://www.hanainsure.co.kr/',
    sortOrder: 70,
  },
  {
    category: 'non_life',
    name: '롯데손해보험',
    logoFile: 'lotte_insurance',
    salesUrl: 'https://sales.lotteins.co.kr/',
    homepageUrl: 'https://www.lotteins.co.kr/',
    disclosureUrl: 'https://www.lotteins.co.kr/web/C/D/H/cdh190.jsp',
    claimUrl: 'https://www.lotteins.co.kr/',
    sortOrder: 80,
  },
  {
    category: 'non_life',
    name: '한화손해보험',
    logoFile: 'hanwha_general',
    salesUrl: 'https://www.hwgeneralins.com/',
    homepageUrl: 'https://www.hwgeneralins.com/',
    disclosureUrl: 'https://www.hwgeneralins.com/notice/ir/product-ing01.do',
    claimUrl: 'https://www.hwgeneralins.com/',
    sortOrder: 90,
  },
  {
    category: 'non_life',
    name: '흥국화재',
    logoFile: 'heungkuk_fire',
    salesUrl: 'https://sales.heungkukfire.co.kr/',
    homepageUrl: 'https://www.heungkukfire.co.kr/',
    disclosureUrl: 'https://www.heungkukfire.co.kr/FRW/announce/insGoodsGongsiSale.do',
    claimUrl: 'https://www.heungkukfire.co.kr/',
    sortOrder: 100,
  },
  {
    category: 'non_life',
    name: 'MG손해보험',
    logoFile: 'mg_insurance',
    salesUrl: 'https://www.mggeneralins.com/',
    homepageUrl: 'https://www.mggeneralins.com/',
    disclosureUrl: 'https://www.mggeneralins.com/PB031220DM.scp?menuId=MN0803006',
    claimUrl: 'https://www.mggeneralins.com/',
    sortOrder: 110,
  },
  {
    category: 'non_life',
    name: 'AIG손해보험',
    logoFile: 'aig_insurance',
    salesUrl: 'https://www.aig.co.kr/',
    homepageUrl: 'https://www.aig.co.kr/',
    disclosureUrl: '',
    claimUrl: 'https://www.aig.co.kr/',
    sortOrder: 120,
  },
  {
    category: 'non_life',
    name: '에이스손해보험',
    logoFile: 'ace_insurance',
    salesUrl: 'https://www.aceinsurance.co.kr/',
    homepageUrl: 'https://www.aceinsurance.co.kr/',
    disclosureUrl: 'https://ec.aceinsurance.co.kr/html/acelimited/company/publish/commodity_publish02_m.html',
    claimUrl: 'https://www.aceinsurance.co.kr/',
    sortOrder: 130,
  },
  {
    category: 'life',
    name: '라이나생명',
    logoFile: 'lina_life',
    salesUrl: 'https://www.lina.co.kr/',
    homepageUrl: 'https://www.lina.co.kr/',
    disclosureUrl: 'https://www.lina.co.kr/disclosure/product-public-announcement/product-guide',
    claimUrl: 'https://www.lina.co.kr/',
    sortOrder: 10,
  },
  {
    category: 'life',
    name: 'DB생명',
    logoFile: 'db_life',
    salesUrl: 'https://www.dblife.co.kr/',
    homepageUrl: 'https://www.dblife.co.kr/',
    disclosureUrl: '',
    claimUrl: 'https://www.dblife.co.kr/',
    sortOrder: 20,
  },
  {
    category: 'life',
    name: '삼성생명',
    logoFile: 'samsung_life',
    salesUrl: 'https://www.samsunglife.com/',
    homepageUrl: 'https://www.samsunglife.com/',
    disclosureUrl: 'https://www.samsunglife.com/individual/products/disclosure/sales/PDO-PRPRI010110M',
    claimUrl: 'https://www.samsunglife.com/',
    sortOrder: 30,
  },
  {
    category: 'life',
    name: '미래에셋생명',
    logoFile: 'mirae_asset_life',
    salesUrl: 'https://www.miraeassetlife.com/',
    homepageUrl: 'https://www.miraeassetlife.com/',
    disclosureUrl: '',
    claimUrl: 'https://www.miraeassetlife.com/',
    sortOrder: 40,
  },
  {
    category: 'life',
    name: '동양생명',
    logoFile: 'tongyang_life',
    salesUrl: 'https://www.orientalife.co.kr/',
    homepageUrl: 'https://www.orientalife.co.kr/',
    disclosureUrl: 'https://pbano.myangel.co.kr/paging/WE_AC_WEPAAP020100L',
    claimUrl: 'https://www.orientalife.co.kr/',
    sortOrder: 50,
  },
  {
    category: 'life',
    name: '한화생명',
    logoFile: 'hanwha_life',
    salesUrl: 'https://www.hanwhalife.com/',
    homepageUrl: 'https://www.hanwhalife.com/',
    disclosureUrl: 'https://www.hanwhalife.com/main/disclosure/main/DF_0000000_P00000.do',
    claimUrl: 'https://www.hanwhalife.com/',
    sortOrder: 60,
  },
  {
    category: 'life',
    name: 'NH농협생명',
    logoFile: 'nh_life',
    salesUrl: 'https://www.nhlife.co.kr/',
    homepageUrl: 'https://www.nhlife.co.kr/',
    disclosureUrl: 'https://www.nhlife.co.kr/ho/on/HOON0004M00.nhl',
    claimUrl: 'https://www.nhlife.co.kr/',
    sortOrder: 70,
  },
  {
    category: 'life',
    name: 'DGB생명',
    logoFile: 'dgb_life',
    salesUrl: 'https://www.dgblife.co.kr/',
    homepageUrl: 'https://www.dgblife.co.kr/',
    disclosureUrl: 'https://www.imlifeins.co.kr/BA/BA_A020.do',
    claimUrl: 'https://www.dgblife.co.kr/',
    sortOrder: 80,
  },
  {
    category: 'life',
    name: 'ABL생명',
    logoFile: 'abl_life',
    salesUrl: 'https://www.abllife.co.kr/',
    homepageUrl: 'https://www.abllife.co.kr/',
    disclosureUrl: '',
    claimUrl: 'https://www.abllife.co.kr/',
    sortOrder: 90,
  },
  {
    category: 'life',
    name: '처브라이프생명',
    logoFile: 'chubb_life',
    salesUrl: 'https://www.chubblife.co.kr/',
    homepageUrl: 'https://www.chubblife.co.kr/',
    disclosureUrl: 'https://www.chubblife.co.kr/front/official/sale/list.do',
    claimUrl: 'https://www.chubblife.co.kr/',
    sortOrder: 100,
  },
  {
    category: 'life',
    name: '신한라이프생명',
    logoFile: 'shinhan_life',
    salesUrl: 'https://www.shinhanlife.co.kr/',
    homepageUrl: 'https://www.shinhanlife.co.kr/',
    disclosureUrl: '',
    claimUrl: 'https://www.shinhanlife.co.kr/',
    sortOrder: 110,
  },
  {
    category: 'life',
    name: 'KB라이프생명',
    logoFile: 'kb_life',
    salesUrl: 'https://www.kblife.co.kr/',
    homepageUrl: 'https://www.kblife.co.kr/',
    disclosureUrl: 'https://www.kblife.co.kr/customer-common/guideToProductPublicNoticeOfficeProductPublicNotice.do',
    claimUrl: 'https://www.kblife.co.kr/',
    sortOrder: 120,
  },
  {
    category: 'life',
    name: '흥국생명',
    logoFile: 'heungkuk_life',
    salesUrl: 'https://www.heungkuklife.co.kr/',
    homepageUrl: 'https://www.heungkuklife.co.kr/',
    disclosureUrl: 'https://www.heungkuklife.co.kr/front/public/saleProduct.do?searchFlgSale=Y',
    claimUrl: 'https://www.heungkuklife.co.kr/',
    sortOrder: 130,
  },
  {
    category: 'life',
    name: '교보생명',
    logoFile: 'kyobo_life',
    salesUrl: 'https://www.kyobo.com/',
    homepageUrl: 'https://www.kyobo.com/',
    disclosureUrl: '',
    claimUrl: 'https://www.kyobo.com/',
    sortOrder: 140,
  },
  {
    category: 'life',
    name: '메트라이프생명',
    logoFile: 'metlife',
    salesUrl: 'https://www.metlife.co.kr/',
    homepageUrl: 'https://www.metlife.co.kr/',
    disclosureUrl: 'https://brand.metlife.co.kr/pn/paReal/insuProductDisclMain.do',
    claimUrl: 'https://www.metlife.co.kr/',
    sortOrder: 150,
  },
  {
    category: 'life',
    name: 'KDB생명',
    logoFile: 'kdb_life',
    salesUrl: 'https://www.kdblife.co.kr/',
    homepageUrl: 'https://www.kdblife.co.kr/',
    disclosureUrl: 'https://www.kdblife.com/ajax.do?scrId=HDLMA000M00P&pcmode=1',
    claimUrl: 'https://www.kdblife.co.kr/',
    sortOrder: 160,
  },
  {
    category: 'life',
    name: '푸본현대생명',
    logoFile: 'fubon_hyundai_life',
    salesUrl: 'https://www.fubonhyundailife.com/',
    homepageUrl: 'https://www.fubonhyundailife.com/',
    disclosureUrl: '',
    claimUrl: 'https://www.fubonhyundailife.com/',
    sortOrder: 170,
  },
  {
    category: 'life',
    name: 'BNP파리바카디프생명',
    logoFile: 'bnp_cardif_life',
    salesUrl: 'https://www.cardif.co.kr/',
    homepageUrl: 'https://www.cardif.co.kr/',
    disclosureUrl: 'https://www.cardif.co.kr/disclosure/papap001.do',
    claimUrl: 'https://www.cardif.co.kr/',
    sortOrder: 180,
  },
  {
    category: 'life',
    name: 'IBK연금보험',
    logoFile: 'ibk_pension',
    salesUrl: 'https://www.ibklife.co.kr/',
    homepageUrl: 'https://www.ibklife.co.kr/',
    disclosureUrl: 'https://www.ibki.co.kr/process/HP_PBANO_PRC_LIST',
    claimUrl: 'https://www.ibklife.co.kr/',
    sortOrder: 190,
  },
]
