import type {
  CustomerFieldRegistryEntry,
} from './customerTemplateRegistry.types'

/** Registry 스키마와 동기화되는 기본 버전 문자열 */
const SV = '0.1'

const v = ({
  validation = {},
}: {
  validation?: CustomerFieldRegistryEntry['validation']
} = {}): CustomerFieldRegistryEntry['validation'] => ({ ...validation })

/**
 * Canonical fieldKey → 정의.
 * 레거시 숏키(alias) 해석은 registry utils 의 alias 맵으로 처리한다.
 */
export const CUSTOMER_FIELD_REGISTRY_BY_KEY = Object.freeze({
  'customer.name': Object.freeze({
    fieldKey: 'customer.name',
    label: '이름',
    category: 'core',
    domains: Object.freeze(['core', 'government', 'gov_support', 'gym'] as const),
    widget: 'text',
    valueType: 'string',
    requiredDefault: true,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 200 } }),
    description: '고객 표시명·실명.',
    storageMapping: { kind: 'legacyColumn', column: 'name' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.phone': Object.freeze({
    fieldKey: 'customer.phone',
    label: '연락처',
    category: 'contact',
    domains: Object.freeze(['core', 'government', 'gov_support', 'gym'] as const),
    widget: 'phone',
    valueType: 'string',
    requiredDefault: true,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 64 } }),
    description: '대표 전화번호.',
    storageMapping: { kind: 'legacyColumn', column: 'phone' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.email': Object.freeze({
    fieldKey: 'customer.email',
    label: '이메일',
    category: 'contact',
    domains: Object.freeze(['core']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: false,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 320 } }),
    description: '선택 연락처. 레거시 스키마에는 없을 수 있음.',
    storageMapping: {
      kind: 'unmapped',
      reason: 'legacy customers row — optional future column',
    },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'customer.address': Object.freeze({
    fieldKey: 'customer.address',
    label: '주소',
    category: 'contact',
    domains: Object.freeze(['core', 'government', 'gov_support', 'gym'] as const),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '우편/거주 주소 텍스트.',
    storageMapping: { kind: 'legacyColumn', column: 'address' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.birthDate': Object.freeze({
    fieldKey: 'customer.birthDate',
    label: '생년월일',
    category: 'personal',
    domains: Object.freeze(['core', 'insurance', 'government', 'gov_support', 'gym'] as const),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'sensitive',
    validation: v(),
    description: '생년월일(ISO date string 등 저장 형식은 저장소 책임).',
    storageMapping: { kind: 'legacyColumn', column: 'birth_date' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.memo': Object.freeze({
    fieldKey: 'customer.memo',
    label: '메모',
    category: 'document',
    domains: Object.freeze(['core', 'government', 'gov_support', 'gym'] as const),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description:
      '인라인/요약 메모. 실제 저장은 notes JSON·별도 테이블일 수 있다.',
    storageMapping: { kind: 'jsonPath', path: 'notes' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.status': Object.freeze({
    fieldKey: 'customer.status',
    label: '상태',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: false,
    privacyLevel: 'normal',
    validation: v(),
    description: '워크플로 상태(프로젝트 enum 연결 예정).',
    storageMapping: { kind: 'unmapped', reason: 'not yet in legacy row' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'customer.assigneeUserId': Object.freeze({
    fieldKey: 'customer.assigneeUserId',
    label: '담당자',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'select',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '담당 설계사/직원 user id.',
    storageMapping: { kind: 'legacyColumn', column: 'user_id' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.tags': Object.freeze({
    fieldKey: 'customer.tags',
    label: '태그',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'tags',
    valueType: 'json',
    requiredDefault: false,
    visibleDefault: false,
    privacyLevel: 'normal',
    validation: v(),
    description: '다중 태그. 레거시는 미구현일 수 있음.',
    storageMapping: {
      kind: 'unmapped',
      reason: 'tags storage TBD — separate table or JSON',
    },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'customer.createdAt': Object.freeze({
    fieldKey: 'customer.createdAt',
    label: '등록일',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'readonly-text',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '레코드 생성 시각.',
    storageMapping: { kind: 'legacyColumn', column: 'created_at' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  /** insuranceCustomerTemplate v0.1 의 `isFavorite` 와 매핑 */
  'customer.isFavorite': Object.freeze({
    fieldKey: 'customer.isFavorite',
    label: '중요 고객',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'boolean',
    valueType: 'boolean',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '즐겨찾기/중요 플래그.',
    storageMapping: { kind: 'legacyColumn', column: 'is_favorite' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  /** insuranceCustomerTemplate v0.1 의 `customerCode` 와 매핑 */
  'customer.customerCode': Object.freeze({
    fieldKey: 'customer.customerCode',
    label: '고객번호',
    category: 'core',
    domains: Object.freeze(['core']),
    widget: 'readonly-text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 64 } }),
    description: '내부 고객 식별 코드.',
    storageMapping: { kind: 'legacyColumn', column: 'customer_code' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.carrier': Object.freeze({
    fieldKey: 'customer.carrier',
    label: '통신사',
    category: 'contact',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: {
        enumValues: Object.freeze(['SK', 'KT', 'LGU+', '알뜰폰', '기타']),
      },
    }),
    description: '이동통신사.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  /** 국가지원 CRM 주민번호(보험 레거시 `insurance.ssn` 과 별도). */
  'customer.ssn': Object.freeze({
    fieldKey: 'customer.ssn',
    label: '주민번호',
    category: 'personal',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'identifying',
    validation: v({ validation: { maxLength: 20 } }),
    description: '민감정보. 마스킹·권한은 별도 레이어.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM — encryption TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'customer.homeType': Object.freeze({
    fieldKey: 'customer.homeType',
    label: '자택형태',
    category: 'contact',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: {
        enumValues: Object.freeze(['자가', '전세', '월세', '가족소유', '기타']),
      },
    }),
    description: '거주 형태.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'customer.deposit': Object.freeze({
    fieldKey: 'customer.deposit',
    label: '보증금',
    category: 'contact',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '전세·임대 보증금(원).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'customer.monthlyRent': Object.freeze({
    fieldKey: 'customer.monthlyRent',
    label: '월세',
    category: 'contact',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '월세(원).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'customer.creditScoreKcb': Object.freeze({
    fieldKey: 'customer.creditScoreKcb',
    label: '신용점수 KCB',
    category: 'personal',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'sensitive',
    validation: v({ validation: { minimum: 0, maximum: 1000 } }),
    description: 'KCB 신용점수.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'customer.creditScoreNice': Object.freeze({
    fieldKey: 'customer.creditScoreNice',
    label: '신용점수 NICE',
    category: 'personal',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'sensitive',
    validation: v({ validation: { minimum: 0, maximum: 1000 } }),
    description: 'NICE 신용점수.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'insurance.ssn': Object.freeze({
    fieldKey: 'insurance.ssn',
    label: '주민등록번호',
    category: 'personal',
    domains: Object.freeze(['insurance']),
    widget: 'ssn',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'identifying',
    validation: v({ validation: { pattern: '^\\d{6}-\\d{7}$' } }),
    description: '식별번호. 마스킹·저장 규격은 규제 레이어.',
    storageMapping: { kind: 'legacyColumn', column: 'ssn' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.insuranceAge': Object.freeze({
    fieldKey: 'insurance.insuranceAge',
    label: '보험나이',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0, maximum: 150 } }),
    description: '상령·보험나이 표시값(파생 가능).',
    storageMapping: { kind: 'legacyColumn', column: 'insurance_age' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.nextAgeDate': Object.freeze({
    fieldKey: 'insurance.nextAgeDate',
    label: '상령일',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '다음 상령일.',
    storageMapping: { kind: 'legacyColumn', column: 'next_age_date' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.gender': Object.freeze({
    fieldKey: 'customer.gender',
    label: '성별',
    category: 'personal',
    domains: Object.freeze(['core', 'insurance', 'government', 'gov_support', 'gym'] as const),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { enumValues: Object.freeze(['M', 'F', 'OTHER']) } }),
    description: '성별 선택.',
    storageMapping: { kind: 'legacyColumn', column: 'gender' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.job': Object.freeze({
    fieldKey: 'customer.job',
    label: '직업·회사',
    category: 'personal',
    domains: Object.freeze(['core', 'insurance']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 500 } }),
    description: '직업·근무처.',
    storageMapping: { kind: 'legacyColumn', column: 'job' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.height': Object.freeze({
    fieldKey: 'customer.height',
    label: '키',
    category: 'personal',
    domains: Object.freeze(['core', 'insurance', 'gym']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'sensitive',
    validation: v({ validation: { maxLength: 32 } }),
    description: '신장(cm 등 단위 문자열 허용).',
    storageMapping: { kind: 'legacyColumn', column: 'height' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'customer.weight': Object.freeze({
    fieldKey: 'customer.weight',
    label: '몸무게',
    category: 'personal',
    domains: Object.freeze(['core', 'insurance', 'gym']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'sensitive',
    validation: v({ validation: { maxLength: 32 } }),
    description: '체중.',
    storageMapping: { kind: 'legacyColumn', column: 'weight' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.medical': Object.freeze({
    fieldKey: 'insurance.medical',
    label: '의료·건강 고지',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'sensitive',
    validation: v(),
    description: '의료 고지 요약 텍스트.',
    storageMapping: { kind: 'legacyColumn', column: 'medical' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.drivingText': Object.freeze({
    fieldKey: 'insurance.drivingText',
    label: '운전(텍스트)',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '운전 상태 자유 입력.',
    storageMapping: { kind: 'legacyColumn', column: 'driving' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.isDriver': Object.freeze({
    fieldKey: 'insurance.isDriver',
    label: '운전 여부',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    widget: 'boolean',
    valueType: 'boolean',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '운전자 여부.',
    storageMapping: { kind: 'legacyColumn', column: 'is_driver' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'vehicle.carType': Object.freeze({
    fieldKey: 'vehicle.carType',
    label: '차종',
    category: 'vehicle',
    domains: Object.freeze(['insurance']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 120 } }),
    description: '대표 차종(복수 차량 시 expansion row).',
    storageMapping: { kind: 'legacyColumn', column: 'car_type' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'vehicle.carNumber': Object.freeze({
    fieldKey: 'vehicle.carNumber',
    label: '차량번호',
    category: 'vehicle',
    domains: Object.freeze(['insurance']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 32 } }),
    description: '번호판 번호.',
    storageMapping: { kind: 'legacyColumn', column: 'car_number' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'vehicle.carModel': Object.freeze({
    fieldKey: 'vehicle.carModel',
    label: '차량 모델',
    category: 'vehicle',
    domains: Object.freeze(['insurance']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 200 } }),
    description: '세부 모델명.',
    storageMapping: { kind: 'legacyColumn', column: 'car_model' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'vehicle.carYear': Object.freeze({
    fieldKey: 'vehicle.carYear',
    label: '차량 연식',
    category: 'vehicle',
    domains: Object.freeze(['insurance']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 8 } }),
    description: '연식 문자열 또는 연도 숫자.',
    storageMapping: { kind: 'legacyColumn', column: 'car_year' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'insurance.renewalDate': Object.freeze({
    fieldKey: 'insurance.renewalDate',
    label: '만기·갱신 예정일',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '자동차/대표증권 등 갱신일.',
    storageMapping: { kind: 'legacyColumn', column: 'renewal_date' },
    status: 'active',
    introducedInSchemaVersion: SV,
  }),
  'gym.membershipType': Object.freeze({
    fieldKey: 'gym.membershipType',
    label: '회원권 유형',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '헬스장 회원 유형.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.membershipStartDate': Object.freeze({
    fieldKey: 'gym.membershipStartDate',
    label: '회원권 시작일',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '시작일.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.membershipEndDate': Object.freeze({
    fieldKey: 'gym.membershipEndDate',
    label: '회원권 만료일',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '회원권 만료·종료일.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.ptCount': Object.freeze({
    fieldKey: 'gym.ptCount',
    label: 'PT 잔여',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: 'PT 회차 카운터.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.workoutGoal': Object.freeze({
    fieldKey: 'gym.workoutGoal',
    label: '운동 목표',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '목표 서술.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.memberCode': Object.freeze({
    fieldKey: 'gym.memberCode',
    label: '회원번호',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 64 } }),
    description: '시설 내 회원 식별 코드.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.programName': Object.freeze({
    fieldKey: 'gym.programName',
    label: '프로그램명',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 200 } }),
    description: '등록 프로그램·수업 명칭.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.remainingSessions': Object.freeze({
    fieldKey: 'gym.remainingSessions',
    label: '잔여 횟수',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '회원권·패키지 잔여 이용 횟수.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.trainerName': Object.freeze({
    fieldKey: 'gym.trainerName',
    label: '담당 트레이너',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 120 } }),
    description: '담당 코치·트레이너 표시명.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.healthNotes': Object.freeze({
    fieldKey: 'gym.healthNotes',
    label: '건강 메모',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'sensitive',
    validation: v(),
    description: '부상·질환·처방 등 운동 시 주의 메모.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.attendanceStatus': Object.freeze({
    fieldKey: 'gym.attendanceStatus',
    label: '출석 상태',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '최근 출석 요약 상태.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.lastVisitDate': Object.freeze({
    fieldKey: 'gym.lastVisitDate',
    label: '마지막 방문일',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '시설 마지막 방문 일자.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.nextReservationDate': Object.freeze({
    fieldKey: 'gym.nextReservationDate',
    label: '다음 예약일',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '다음 예약·수업 일정.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.paymentStatus': Object.freeze({
    fieldKey: 'gym.paymentStatus',
    label: '결제 상태',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '회비·패키지 결제 상태.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gym.renewalStatus': Object.freeze({
    fieldKey: 'gym.renewalStatus',
    label: '재등록 상태',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '만료 전후 재등록·연장 상태.',
    storageMapping: { kind: 'unmapped', reason: 'future gym schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'alcohol.businessNumber': Object.freeze({
    fieldKey: 'alcohol.businessNumber',
    label: '사업자등록번호',
    category: 'business',
    domains: Object.freeze(['alcohol']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '도매 거래처 사업자 번호.',
    storageMapping: { kind: 'unmapped', reason: 'future alcohol schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'alcohol.storeName': Object.freeze({
    fieldKey: 'alcohol.storeName',
    label: '매장명',
    category: 'business',
    domains: Object.freeze(['alcohol']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '거래처/매장명.',
    storageMapping: { kind: 'unmapped', reason: 'future alcohol schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'alcohol.deliveryAddress': Object.freeze({
    fieldKey: 'alcohol.deliveryAddress',
    label: '배송지',
    category: 'contact',
    domains: Object.freeze(['alcohol']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '배달 주소.',
    storageMapping: { kind: 'unmapped', reason: 'future alcohol schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'alcohol.paymentTerms': Object.freeze({
    fieldKey: 'alcohol.paymentTerms',
    label: '결제 조건',
    category: 'business',
    domains: Object.freeze(['alcohol']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '결제·세금계산서 조건.',
    storageMapping: { kind: 'unmapped', reason: 'future alcohol schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'alcohol.orderCycle': Object.freeze({
    fieldKey: 'alcohol.orderCycle',
    label: '발주 주기',
    category: 'business',
    domains: Object.freeze(['alcohol']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '정기 발주 패턴.',
    storageMapping: { kind: 'unmapped', reason: 'future alcohol schema' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.name': Object.freeze({
    fieldKey: 'business.name',
    label: '사업장명칭',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 300 } }),
    description: '상호·사업장 명칭.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.ownerName': Object.freeze({
    fieldKey: 'business.ownerName',
    label: '대표자명',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 200 } }),
    description: '대표자 실명.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.openedAt': Object.freeze({
    fieldKey: 'business.openedAt',
    label: '개업년월일',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '사업자 개업일.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.registrationNumber': Object.freeze({
    fieldKey: 'business.registrationNumber',
    label: '사업자등록번호',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 32 } }),
    description: '국세청 사업자번호.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.address': Object.freeze({
    fieldKey: 'business.address',
    label: '사업장 소재지',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '사업장 주소.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.category': Object.freeze({
    fieldKey: 'business.category',
    label: '사업자 종목',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 200 } }),
    description: '업종·종목.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.type': Object.freeze({
    fieldKey: 'business.type',
    label: '업태',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 120 } }),
    description: '업태.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.placeType': Object.freeze({
    fieldKey: 'business.placeType',
    label: '사업장 형태',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: {
        enumValues: Object.freeze([
          '자가',
          '임대',
          '공유오피스',
          '무점포',
          '온라인',
          '기타',
        ]),
      },
    }),
    description: '사업장 형태.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.phone': Object.freeze({
    fieldKey: 'business.phone',
    label: '사업장 번호',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'phone',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 64 } }),
    description: '사업장 연락처.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.vatReported': Object.freeze({
    fieldKey: 'business.vatReported',
    label: '부가세 신고 유/무',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: { enumValues: Object.freeze(['유', '무', '확인필요']) },
    }),
    description: '부가가치세 신고 여부.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.incomeProofAvailable': Object.freeze({
    fieldKey: 'business.incomeProofAvailable',
    label: '소득금액증명원 발급 여부',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: { enumValues: Object.freeze(['가능', '불가', '확인필요']) },
    }),
    description: '국세 소득금액증명원 발급 가능 여부.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.annualIncome': Object.freeze({
    fieldKey: 'business.annualIncome',
    label: '연소득',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'sensitive',
    validation: v({ validation: { minimum: 0 } }),
    description: '연간 소득(원).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'business.taxArrears': Object.freeze({
    fieldKey: 'business.taxArrears',
    label: '세금 체납 여부',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: { enumValues: Object.freeze(['유', '무', '확인필요']) },
    }),
    description: '세금 체납 여부.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.productName': Object.freeze({
    fieldKey: 'gov.productName',
    label: '접수상품명',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 300 } }),
    description: '접수한 상품·패키지 명칭.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.applicationType': Object.freeze({
    fieldKey: 'gov.applicationType',
    label: '신청 유형',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: {
        enumValues: Object.freeze([
          '정책자금',
          '지원금',
          '보조금',
          '대출',
          '컨설팅',
          '기타',
        ]),
      },
    }),
    description: '지원 신청 유형.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.caseNumber': Object.freeze({
    fieldKey: 'gov.caseNumber',
    label: '접수번호',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 120 } }),
    description: '내부·기관 접수 번호.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.programName': Object.freeze({
    fieldKey: 'gov.programName',
    label: '지원사업명',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 300 } }),
    description: '정부·지자체 사업명.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.agency': Object.freeze({
    fieldKey: 'gov.agency',
    label: '관할 기관',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 200 } }),
    description: '주관·관할 기관.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.department': Object.freeze({
    fieldKey: 'gov.department',
    label: '담당 부서',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 200 } }),
    description: '기관 내 담당 부서.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.status': Object.freeze({
    fieldKey: 'gov.status',
    label: '진행 상태',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: {
        enumValues: Object.freeze([
          '접수',
          '검토중',
          '진행가능',
          '계약서발송',
          '계약완료',
          '서류준비',
          '보완요청',
          '제출완료',
          '심사중',
          '승인',
          '반려',
          '보류',
          '진행불가',
          '완료',
        ]),
      },
    }),
    description: '지원 건 전체 진행 단계.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.submittedAt': Object.freeze({
    fieldKey: 'gov.submittedAt',
    label: '접수일',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '접수일.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.dueDate': Object.freeze({
    fieldKey: 'gov.dueDate',
    label: '마감일',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '제출·보완 등 마감일.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.assignee': Object.freeze({
    fieldKey: 'gov.assignee',
    label: '담당자',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 200 } }),
    description: '건 담당자 표시명 또는 id 문자열.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  // TODO: checklist 위젯 지원 시 위젯 타입 전환
  'gov.requiredDocuments': Object.freeze({
    fieldKey: 'gov.requiredDocuments',
    label: '필요 서류',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '제출 필요 서류 목록(임시 textarea).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.supportAmount': Object.freeze({
    fieldKey: 'gov.supportAmount',
    label: '필요자금',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '신청·필요 금액(원).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.approvalAmount': Object.freeze({
    fieldKey: 'gov.approvalAmount',
    label: '승인금액',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '승인된 금액(원).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.result': Object.freeze({
    fieldKey: 'gov.result',
    label: '결과',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: {
        enumValues: Object.freeze(['진행중', '승인', '반려', '보류', '취소', '완료']),
      },
    }),
    description: '지원 심의 결과.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.rejectionReason': Object.freeze({
    fieldKey: 'gov.rejectionReason',
    label: '반려 사유',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '반려·불승 시 사유.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.supplementRequest': Object.freeze({
    fieldKey: 'gov.supplementRequest',
    label: '보완 요청 내용',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '보완 요청 상세.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  /** 레거시 호환 — 신규 화면은 gov.programName·gov.status 우선 */
  'gov.supportProgram': Object.freeze({
    fieldKey: 'gov.supportProgram',
    label: '지원 프로그램',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: false,
    privacyLevel: 'normal',
    validation: v(),
    description: '구버전 필드. 프로그램명은 gov.programName 권장.',
    storageMapping: { kind: 'unmapped', reason: 'legacy alias' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.documentStatus': Object.freeze({
    fieldKey: 'gov.documentStatus',
    label: '서류 상태(구)',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: false,
    privacyLevel: 'normal',
    validation: v(),
    description: '구버전 필드. 진행은 gov.status 권장.',
    storageMapping: { kind: 'unmapped', reason: 'legacy' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'gov.applicationStatus': Object.freeze({
    fieldKey: 'gov.applicationStatus',
    label: '신청 상태(구)',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: false,
    privacyLevel: 'normal',
    validation: v(),
    description: '구버전 필드. 진행은 gov.status 권장.',
    storageMapping: { kind: 'unmapped', reason: 'legacy' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  // TODO: repeatable 행 편집 지원 시 loan 서브레코드로 이관
  'loan.existingLoans': Object.freeze({
    fieldKey: 'loan.existingLoans',
    label: '기대출',
    category: 'loan',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '상호/잔액/일자 다건 — 임시 자유서술.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'loan.companyName': Object.freeze({
    fieldKey: 'loan.companyName',
    label: '상호명 / 금융사명',
    category: 'loan',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 200 } }),
    description: '대출 기관 명.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'loan.remainingAmount': Object.freeze({
    fieldKey: 'loan.remainingAmount',
    label: '남은 금액',
    category: 'loan',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '잔여 원금(원).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'loan.receivedAt': Object.freeze({
    fieldKey: 'loan.receivedAt',
    label: '받은 날짜',
    category: 'loan',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '대출 실행일.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'loan.productType': Object.freeze({
    fieldKey: 'loan.productType',
    label: '상품 구분',
    category: 'loan',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: {
        enumValues: Object.freeze([
          '일반대출',
          '정책상품',
          '카드론',
          '현금서비스',
          '기타',
        ]),
      },
    }),
    description: '대출 상품 유형.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'loan.memo': Object.freeze({
    fieldKey: 'loan.memo',
    label: '기대출 메모',
    category: 'loan',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '기대출 관련 메모.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.totalFee': Object.freeze({
    fieldKey: 'contract.totalFee',
    label: '수임료 총액',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '수임료 합계(원).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.depositAmount': Object.freeze({
    fieldKey: 'contract.depositAmount',
    label: '계약금',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '계약금(원).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.balanceAmount': Object.freeze({
    fieldKey: 'contract.balanceAmount',
    label: '잔금',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '잔금(원).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.paidAmount': Object.freeze({
    fieldKey: 'contract.paidAmount',
    label: '입금액',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '누적 입금액(원).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.unpaidAmount': Object.freeze({
    fieldKey: 'contract.unpaidAmount',
    label: '미수금',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '미수 잔액(원).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.paymentStatus': Object.freeze({
    fieldKey: 'contract.paymentStatus',
    label: '입금 상태',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: {
        enumValues: Object.freeze([
          '미정',
          '계약금대기',
          '계약금완료',
          '잔금대기',
          '부분입금',
          '완납',
          '미수',
          '환불',
          '취소',
        ]),
      },
    }),
    description: '수임료 입금 진행 상태.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.paymentDueDate': Object.freeze({
    fieldKey: 'contract.paymentDueDate',
    label: '입금 예정일',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '다음 입금 예정일.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.depositPaidAt': Object.freeze({
    fieldKey: 'contract.depositPaidAt',
    label: '계약금 입금일',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '계약금 입금 일자.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.balancePaidAt': Object.freeze({
    fieldKey: 'contract.balancePaidAt',
    label: '잔금 입금일',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '잔금 입금 일자.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.refundAmount': Object.freeze({
    fieldKey: 'contract.refundAmount',
    label: '환불금',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '환불 금액(원).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.paymentMemo': Object.freeze({
    fieldKey: 'contract.paymentMemo',
    label: '수임료/입금 메모',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '입금·정산 메모.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.certificateDelegated': Object.freeze({
    fieldKey: 'contract.certificateDelegated',
    label: '인증서 위임 여부',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: { enumValues: Object.freeze(['위임', '미위임', '확인필요']) },
    }),
    description: '공동·금융 인증서 위임.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.certificateType': Object.freeze({
    fieldKey: 'contract.certificateType',
    label: '인증서 종류',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: {
        enumValues: Object.freeze([
          '금융인증서',
          '공동인증서',
          '기타',
          '없음',
        ]),
      },
    }),
    description: '사용 인증서 유형.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.signedAt': Object.freeze({
    fieldKey: 'contract.signedAt',
    label: '계약일',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '계약 체결일.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.status': Object.freeze({
    fieldKey: 'contract.status',
    label: '계약 상태',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: {
        enumValues: Object.freeze([
          '계약전',
          '계약서발송',
          '서명완료',
          '취소',
          '보류',
        ]),
      },
    }),
    description: '수임 계약 진행 상태.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'contract.memo': Object.freeze({
    fieldKey: 'contract.memo',
    label: '계약 특이사항',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'textarea',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '계약 특이사항.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  // TODO: datetime 네이티브 위젯 — 현재 ISO 문자열 text 취급
  'document.signatureStatus': Object.freeze({
    fieldKey: 'document.signatureStatus',
    label: '전자서명 상태',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: {
        enumValues: Object.freeze([
          '미발송',
          '발송완료',
          '열람',
          '서명완료',
          '만료',
          '취소',
        ]),
      },
    }),
    description: '전자서명 요청 상태.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'document.lastSentAt': Object.freeze({
    fieldKey: 'document.lastSentAt',
    label: '최근 문서 발송일',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '발송 시각(임시 문자열·추후 datetime).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'document.lastCompletedAt': Object.freeze({
    fieldKey: 'document.lastCompletedAt',
    label: '최근 문서 완료일',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '완료 시각(임시 문자열·추후 datetime).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'document.completedPdfCount': Object.freeze({
    fieldKey: 'document.completedPdfCount',
    label: '완료 문서 수',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'number',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { minimum: 0 } }),
    description: '서명 완료 건수.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'document.hasLegalEvidence': Object.freeze({
    fieldKey: 'document.hasLegalEvidence',
    label: '법적 로그 여부',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'boolean',
    valueType: 'boolean',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '전자문서 법적 증거 로그 존재.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'document.lastTemplateName': Object.freeze({
    fieldKey: 'document.lastTemplateName',
    label: '최근 발송 문서명',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 300 } }),
    description: '마지막 발송 템플릿/문서명.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'management.source': Object.freeze({
    fieldKey: 'management.source',
    label: '유입 경로',
    category: 'management',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: {
        enumValues: Object.freeze([
          '소개',
          '광고',
          '기존고객',
          '직접문의',
          '제휴',
          '기타',
        ]),
      },
    }),
    description: '고객 유입 채널.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'management.priority': Object.freeze({
    fieldKey: 'management.priority',
    label: '우선순위',
    category: 'management',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({
      validation: { enumValues: Object.freeze(['높음', '보통', '낮음']) },
    }),
    description: '업무 우선순위.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'management.ownerUserId': Object.freeze({
    fieldKey: 'management.ownerUserId',
    label: '담당 영업사원',
    category: 'management',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'select',
    valueType: 'number',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '내부 담당자 user id.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  // TODO: team 엔티티 연동 시 전용 위젯
  'management.teamId': Object.freeze({
    fieldKey: 'management.teamId',
    label: '담당 팀',
    category: 'management',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 64 } }),
    description: '팀 식별자(임시 text).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'management.createdBy': Object.freeze({
    fieldKey: 'management.createdBy',
    label: '등록자',
    category: 'management',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 128 } }),
    description: '등록자 표시명 또는 id.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'management.createdAt': Object.freeze({
    fieldKey: 'management.createdAt',
    label: '등록일',
    category: 'management',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '등록 시각(임시 문자열·추후 datetime).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'management.updatedAt': Object.freeze({
    fieldKey: 'management.updatedAt',
    label: '수정일',
    category: 'management',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '수정 시각(임시 문자열·추후 datetime).',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'management.lastConsultDate': Object.freeze({
    fieldKey: 'management.lastConsultDate',
    label: '최근 상담일',
    category: 'management',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'date',
    valueType: 'date',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v(),
    description: '직접 기입하는 최근 상담일.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  'management.memoSummary': Object.freeze({
    fieldKey: 'management.memoSummary',
    label: '메모 요약',
    category: 'management',
    domains: Object.freeze(['government', 'gov_support']),
    widget: 'text',
    valueType: 'string',
    requiredDefault: false,
    visibleDefault: true,
    privacyLevel: 'normal',
    validation: v({ validation: { maxLength: 500 } }),
    description: '리스트용 한 줄 메모 요약.',
    storageMapping: { kind: 'unmapped', reason: 'government CRM schema TBD' },
    status: 'preview',
    introducedInSchemaVersion: SV,
  }),
  // TODO(registry): domains 리터럴·category와 Entry 타입을 맞추면 `as unknown as` 제거 후보
}) as unknown as Readonly<Record<string, Readonly<CustomerFieldRegistryEntry>>>
