import type { FeatureModuleRegistryEntry } from './customerTemplateRegistry.types'

/**
 * Canonical featureId → 정의.
 * tenant.config.crm.featureFlags 키로 tabId 가 쓰일 수 있으나,
 * 본 레지스트리의 식별자는 featureBinding 문자열이다.
 */
export const FEATURE_MODULE_REGISTRY_BY_ID = Object.freeze({
  'crm-storage-files': Object.freeze({
    featureId: 'crm-storage-files',
    label: '파일',
    category: 'crm-core',
    moduleType: 'detailTab',
    domains: Object.freeze(['core']),
    description: '고객별 파일 저장소 패널.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'CrmFilesConfig',
      type: 'object',
      properties: {},
    }),
    routeBinding: { pathPattern: '/customers/:customerId/files', routeName: 'customer-files' },
    apiBinding: { tag: 'customer-files', pathPrefix: '/customers/:customerId/files' },
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.files']),
    status: 'active',
  }),
  'crm-consultations': Object.freeze({
    featureId: 'crm-consultations',
    label: '상담',
    category: 'crm-core',
    moduleType: 'detailTab',
    domains: Object.freeze(['core']),
    description: '상담 이력·기록 패널.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'CrmConsultationsConfig',
      type: 'object',
      properties: {},
    }),
    routeBinding: {
      pathPattern: '/customers/:customerId/consultations',
      routeName: 'customer-consultations',
    },
    apiBinding: { tag: 'customer-consultations' },
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.consultations']),
    status: 'active',
  }),
  'crm-inline-notes': Object.freeze({
    featureId: 'crm-inline-notes',
    label: '메모',
    category: 'crm-core',
    moduleType: 'detailTab',
    domains: Object.freeze(['core']),
    description: '인라인 메모 패널(워크스페이스·사이드).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({ title: 'CrmMemoConfig', type: 'object', properties: {} }),
    routeBinding: { pathPattern: '/customers/:customerId/memos', routeName: 'customer-memos' },
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.memos']),
    status: 'active',
  }),
  'crm-linked-customers': Object.freeze({
    featureId: 'crm-linked-customers',
    label: '연결 고객',
    category: 'crm-core',
    moduleType: 'panel',
    domains: Object.freeze(['core']),
    description: '가족·법인 등 연결된 고객 관계 관리.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'CrmLinkedCustomersConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.linkedCustomers']),
    status: 'active',
  }),
  'notifications-sms-gateway': Object.freeze({
    featureId: 'notifications-sms-gateway',
    label: 'SMS 알림 게이트웨이',
    category: 'communications',
    moduleType: 'integration',
    domains: Object.freeze(['core']),
    description: 'SMS 발송·템플릿 연계.',
    requiredPermissions: Object.freeze(['notifications.send']),
    configSchema: Object.freeze({
      title: 'SmsGatewayConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['integrations.sms']),
    status: 'active',
  }),
  'esign-send': Object.freeze({
    featureId: 'esign-send',
    label: '전자서명 발송',
    category: 'documents',
    moduleType: 'action',
    domains: Object.freeze(['core']),
    description: '전자서명 문서 발송 플로.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({ title: 'EsignSendConfig', type: 'object', properties: {} }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['integrations.esign']),
    status: 'active',
  }),
  'esign-history': Object.freeze({
    featureId: 'esign-history',
    label: '전자서명 이력',
    category: 'documents',
    moduleType: 'panel',
    domains: Object.freeze(['core']),
    description: '전자서명 요청·완료 이력.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({ title: 'EsignHistoryConfig', type: 'object', properties: {} }),
    dependencies: Object.freeze(['esign-send']),
    tenantConfigKeys: Object.freeze(['integrations.esign']),
    status: 'active',
  }),
  'documents-send': Object.freeze({
    featureId: 'documents-send',
    label: '문서 발송',
    category: 'documents',
    moduleType: 'action',
    domains: Object.freeze(['core']),
    description: '일반 문서 발송(이메일/파일 링크 등).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'DocumentsSendConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['integrations.documents']),
    status: 'preview',
  }),
  'permissions-scope': Object.freeze({
    featureId: 'permissions-scope',
    label: '권한 범위',
    category: 'admin',
    moduleType: 'backgroundJob',
    domains: Object.freeze(['core']),
    description: '조직 단위 접근 통제 노출 훅(횡단 관심사).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'PermissionsScopeConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['permissions.scope']),
    status: 'active',
  }),
  'insurance-ga-excel': Object.freeze({
    featureId: 'insurance-ga-excel',
    label: 'GA 데이터',
    category: 'insurance',
    moduleType: 'detailTab',
    domains: Object.freeze(['insurance']),
    description: 'GA 엑셀 연동 패널.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'InsuranceGaExcelConfig',
      type: 'object',
      properties: {},
    }),
    routeBinding: {
      pathPattern: '/customers/:customerId/ga-excel',
      routeName: 'customer-ga-excel',
    },
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.insuranceGaExcel']),
    status: 'active',
  }),
  'insurance-auto-form': Object.freeze({
    featureId: 'insurance-auto-form',
    label: '자동차 신청',
    category: 'insurance',
    moduleType: 'detailTab',
    domains: Object.freeze(['insurance']),
    description: '자동차 신청 폼 패널.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'InsuranceAutoFormConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.insuranceAutoForm']),
    status: 'active',
  }),
  'insurance-claim-requests': Object.freeze({
    featureId: 'insurance-claim-requests',
    label: '청구 요청',
    category: 'insurance',
    moduleType: 'detailTab',
    domains: Object.freeze(['insurance']),
    description: '보험 청구 요청 리스트/생성 패널.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'InsuranceClaimRequestsConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.insuranceClaimRequests']),
    status: 'active',
  }),
  'insurance-cars': Object.freeze({
    featureId: 'insurance-cars',
    label: '차량',
    category: 'insurance',
    moduleType: 'detailTab',
    domains: Object.freeze(['insurance']),
    description: '다중 차량 관리 패널.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'InsuranceCarsConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.insuranceCars']),
    status: 'active',
  }),
  'insurance-forms': Object.freeze({
    featureId: 'insurance-forms',
    label: '보험 양식',
    category: 'insurance',
    moduleType: 'panel',
    domains: Object.freeze(['insurance']),
    description: '보험 업무 양식·PDF 등.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'InsuranceFormsConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['feature.insuranceForms']),
    status: 'active',
  }),
  'insurer-manager-portal': Object.freeze({
    featureId: 'insurer-manager-portal',
    label: '보험사 관리자 포털',
    category: 'insurance',
    moduleType: 'integration',
    domains: Object.freeze(['insurance']),
    description: '보험사 설계사 전용 뉴스/포털 연계.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'InsurerManagerPortalConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['integrations.insurerManagerPortal']),
    status: 'active',
  }),
  'loss-adjuster-portal': Object.freeze({
    featureId: 'loss-adjuster-portal',
    label: '손해사정사 포털',
    category: 'insurance',
    moduleType: 'integration',
    domains: Object.freeze(['insurance']),
    description: '손해사정사 전용 포털 연계.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'LossAdjusterPortalConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['integrations.lossAdjusterPortal']),
    status: 'active',
  }),
  'workout-automation': Object.freeze({
    featureId: 'workout-automation',
    label: '운동 자동화',
    category: 'industry-extension',
    moduleType: 'backgroundJob',
    domains: Object.freeze(['gym'] as const),
    description: '운동 루틴·기록 자동화(후보).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'WorkoutAutomationConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gym.workoutAutomation']),
    status: 'preview',
  }),
  'membership-expiry-alert': Object.freeze({
    featureId: 'membership-expiry-alert',
    label: '회원권 만료 알림',
    category: 'industry-extension',
    moduleType: 'backgroundJob',
    domains: Object.freeze(['gym'] as const),
    description: '만료 임박 알림 워크플로(후보).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'MembershipExpiryAlertConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gym.membershipAlerts']),
    status: 'preview',
  }),
  'gym-section-basic-info': Object.freeze({
    featureId: 'gym-section-basic-info',
    label: '기본 정보',
    category: 'industry-extension',
    moduleType: 'detailTab',
    domains: Object.freeze(['gym'] as const),
    description: '이름·연락처·주소 등 기본 프로필 섹션(선언).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GymSectionBasicInfoConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gym.section.basicInfo']),
    status: 'preview',
  }),
  'gym-section-membership-program': Object.freeze({
    featureId: 'gym-section-membership-program',
    label: '회원권 / 프로그램 정보',
    category: 'industry-extension',
    moduleType: 'detailTab',
    domains: Object.freeze(['gym'] as const),
    description: '회원권·프로그램·회차 정보 섹션(선언).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GymSectionMembershipProgramConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gym.section.membershipProgram']),
    status: 'preview',
  }),
  'gym-section-fitness-health': Object.freeze({
    featureId: 'gym-section-fitness-health',
    label: '운동 목표 / 건강 메모',
    category: 'industry-extension',
    moduleType: 'detailTab',
    domains: Object.freeze(['gym'] as const),
    description: '운동 목표 및 건강 메모 섹션(선언).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GymSectionFitnessHealthConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gym.section.fitnessHealth']),
    status: 'preview',
  }),
  'gym-section-attendance-reservations': Object.freeze({
    featureId: 'gym-section-attendance-reservations',
    label: '출석 / 예약 이력',
    category: 'industry-extension',
    moduleType: 'detailTab',
    domains: Object.freeze(['gym'] as const),
    description: '출석·예약 이력 패널(선언).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GymSectionAttendanceReservationsConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([
      'gym-attendance-tracking',
      'gym-reservation-management',
    ]),
    tenantConfigKeys: Object.freeze(['gym.section.attendanceReservations']),
    status: 'preview',
  }),
  'gym-section-payment-renewal': Object.freeze({
    featureId: 'gym-section-payment-renewal',
    label: '결제 / 재등록 관리',
    category: 'industry-extension',
    moduleType: 'detailTab',
    domains: Object.freeze(['gym'] as const),
    description: '회비 결제 및 재등록 추적 섹션(선언).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GymSectionPaymentRenewalConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([
      'gym-renewal-followup',
      'gym-session-package',
      'membership-expiry-alert',
    ]),
    tenantConfigKeys: Object.freeze(['gym.section.paymentRenewal']),
    status: 'preview',
  }),
  /* 아래 다섯 featureId는 런타임 모듈이 아니다. 플랫폼 Preview·registry 검증(binding 후보)·문서 목적 선언이다. */
  'gym-attendance-tracking': Object.freeze({
    featureId: 'gym-attendance-tracking',
    label: '체육관 출석 추적',
    category: 'industry-extension',
    moduleType: 'panel',
    domains: Object.freeze(['gym'] as const),
    description: '방문 출석 로그 및 상태(후보·선언).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GymAttendanceTrackingConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gym.attendanceTracking']),
    status: 'preview',
  }),
  'gym-reservation-management': Object.freeze({
    featureId: 'gym-reservation-management',
    label: '체육관 예약 관리',
    category: 'industry-extension',
    moduleType: 'panel',
    domains: Object.freeze(['gym'] as const),
    description: 'PT·수업 예약 생성·변경(후보·선언).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GymReservationMgmtConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gym.reservationManagement']),
    status: 'preview',
  }),
  'gym-session-package': Object.freeze({
    featureId: 'gym-session-package',
    label: '세션·회차 패키지',
    category: 'industry-extension',
    moduleType: 'panel',
    domains: Object.freeze(['gym'] as const),
    description: '횟수권·패키지 잔여량 관리(후보·선언).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GymSessionPackageConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gym.sessionPackage']),
    status: 'preview',
  }),
  'gym-renewal-followup': Object.freeze({
    featureId: 'gym-renewal-followup',
    label: '체육관 재등록 팔로업',
    category: 'industry-extension',
    moduleType: 'integration',
    domains: Object.freeze(['gym'] as const),
    description: '만료 전 재등록 캠페인 워크플로(후보·선언).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GymRenewalFollowupConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gym.renewalFollowup']),
    status: 'preview',
  }),
  'gym-trainer-assignment': Object.freeze({
    featureId: 'gym-trainer-assignment',
    label: '트레이너 배정',
    category: 'industry-extension',
    moduleType: 'panel',
    domains: Object.freeze(['gym'] as const),
    description: '담당 코치 매칭·일정 호환성(후보·선언).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GymTrainerAssignmentConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gym.trainerAssignment']),
    status: 'preview',
  }),
  'alcohol-order-management': Object.freeze({
    featureId: 'alcohol-order-management',
    label: '주류 발주 관리',
    category: 'industry-extension',
    moduleType: 'integration',
    domains: Object.freeze(['alcohol']),
    description: '도매 발주 프로세스(후보).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'AlcoholOrderMgmtConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['alcohol.orders']),
    status: 'preview',
  }),
  'gov-application-workflow': Object.freeze({
    featureId: 'gov-application-workflow',
    label: '정부 지원 신청 워크플로',
    category: 'industry-extension',
    moduleType: 'integration',
    domains: Object.freeze(['gov_support', 'government']),
    description: '지원 신청 단계별 워크플로(후보).',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovApplicationWorkflowConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.applicationWorkflow']),
    status: 'preview',
  }),
  'gov-section-customer': Object.freeze({
    featureId: 'gov-section-customer',
    label: '기본 정보',
    category: 'industry-extension',
    moduleType: 'detailTab',
    domains: Object.freeze(['government', 'gov_support']),
    description: '신청자·연락처·주민번호 등 기본 프로필.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovSectionCustomerConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.section.customer']),
    status: 'preview',
  }),
  'gov-section-business': Object.freeze({
    featureId: 'gov-section-business',
    label: '사업장 정보',
    category: 'industry-extension',
    moduleType: 'detailTab',
    domains: Object.freeze(['government', 'gov_support']),
    description: '사업자·소재지·세무 기본.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovSectionBusinessConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.section.business']),
    status: 'preview',
  }),
  'gov-section-loans': Object.freeze({
    featureId: 'gov-section-loans',
    label: '기대출 정보',
    category: 'industry-extension',
    moduleType: 'detailTab',
    domains: Object.freeze(['government', 'gov_support']),
    description: '기존 대출·정책상품 메모.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovSectionLoansConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.section.loans']),
    status: 'preview',
  }),
  'gov-section-contract': Object.freeze({
    featureId: 'gov-section-contract',
    label: '계약/수임료',
    category: 'industry-extension',
    moduleType: 'detailTab',
    domains: Object.freeze(['government', 'gov_support']),
    description: '수임료·입금·인증서 위임.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovSectionContractConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.section.contract']),
    status: 'preview',
  }),
  'gov-section-documents': Object.freeze({
    featureId: 'gov-section-documents',
    label: '문서/전자서명',
    category: 'documents',
    moduleType: 'detailTab',
    domains: Object.freeze(['government', 'gov_support']),
    description: 'PDF·전자문서·완료 문서·법적 로그.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovSectionDocumentsConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze(['documents-send']),
    tenantConfigKeys: Object.freeze(['gov.section.documents']),
    status: 'preview',
  }),
  'gov-section-internal': Object.freeze({
    featureId: 'gov-section-internal',
    label: '내부 관리',
    category: 'admin',
    moduleType: 'detailTab',
    domains: Object.freeze(['government', 'gov_support']),
    description: '담당·유입·우선순위.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovSectionInternalConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.section.internal']),
    status: 'preview',
  }),
  'gov-document-checklist': Object.freeze({
    featureId: 'gov-document-checklist',
    label: '필요 서류 체크리스트',
    category: 'industry-extension',
    moduleType: 'panel',
    domains: Object.freeze(['government', 'gov_support']),
    description: '제출 서류 관리.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovDocChecklistConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.docChecklist']),
    status: 'preview',
  }),
  'gov-status-tracking': Object.freeze({
    featureId: 'gov-status-tracking',
    label: '진행 상태 추적',
    category: 'industry-extension',
    moduleType: 'panel',
    domains: Object.freeze(['government', 'gov_support']),
    description: '접수부터 결과까지 단계 추적.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovStatusTrackingConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.statusTracking']),
    status: 'preview',
  }),
  'gov-deadline-alert': Object.freeze({
    featureId: 'gov-deadline-alert',
    label: '마감일 알림',
    category: 'industry-extension',
    moduleType: 'backgroundJob',
    domains: Object.freeze(['government', 'gov_support']),
    description: '제출·보완 마감 알림.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovDeadlineAlertConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.deadlineAlert']),
    status: 'preview',
  }),
  'gov-agency-routing': Object.freeze({
    featureId: 'gov-agency-routing',
    label: '관할 기관/부서 관리',
    category: 'industry-extension',
    moduleType: 'panel',
    domains: Object.freeze(['government', 'gov_support']),
    description: '기관·부서·사업명 라우팅.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovAgencyRoutingConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.agencyRouting']),
    status: 'preview',
  }),
  'gov-supplement-request': Object.freeze({
    featureId: 'gov-supplement-request',
    label: '보완 요청 관리',
    category: 'industry-extension',
    moduleType: 'panel',
    domains: Object.freeze(['government', 'gov_support']),
    description: '보완 요청 내용·처리.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovSupplementRequestConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.supplementRequest']),
    status: 'preview',
  }),
  'gov-result-management': Object.freeze({
    featureId: 'gov-result-management',
    label: '결과/승인 관리',
    category: 'industry-extension',
    moduleType: 'panel',
    domains: Object.freeze(['government', 'gov_support']),
    description: '승인금액·반려·결과.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovResultMgmtConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze([]),
    tenantConfigKeys: Object.freeze(['gov.resultManagement']),
    status: 'preview',
  }),
  'gov-activity-hub': Object.freeze({
    featureId: 'gov-activity-hub',
    label: '메모/처리 이력',
    category: 'crm-core',
    moduleType: 'detailTab',
    domains: Object.freeze(['government', 'gov_support']),
    description: '인라인 메모·상담/처리 이력 허브.',
    requiredPermissions: Object.freeze([]),
    configSchema: Object.freeze({
      title: 'GovActivityHubConfig',
      type: 'object',
      properties: {},
    }),
    dependencies: Object.freeze(['crm-inline-notes', 'crm-consultations']),
    tenantConfigKeys: Object.freeze(['gov.activityHub']),
    status: 'preview',
  }),
  // TODO(registry): domains 리터럴을 Entry 타입에 맞추면 `as unknown as` 제거 후보
}) as unknown as Readonly<Record<string, Readonly<FeatureModuleRegistryEntry>>>
