import type { ListColumnRegistryEntry } from './customerTemplateRegistry.types'

/** columnKey(SSOT for listColumns[].columnKey) → 정의 */
export const LIST_COLUMN_REGISTRY_BY_KEY = Object.freeze({
  name: Object.freeze({
    columnKey: 'name',
    label: '이름',
    category: 'core',
    domains: Object.freeze(['core']),
    sourceType: 'field',
    sourceFieldKey: 'customer.name',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '표시 이름(고객 name 컬럼).',
    status: 'active',
  }),
  phone: Object.freeze({
    columnKey: 'phone',
    label: '연락처',
    category: 'contact',
    domains: Object.freeze(['core']),
    sourceType: 'field',
    sourceFieldKey: 'customer.phone',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: false,
    filterable: true,
    visibleDefault: true,
    description: '대표 전화번호.',
    status: 'active',
  }),
  isFavorite: Object.freeze({
    columnKey: 'isFavorite',
    label: '즐겨찾기',
    category: 'core',
    domains: Object.freeze(['core']),
    sourceType: 'field',
    sourceFieldKey: 'customer.isFavorite',
    valueType: 'boolean',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '중요/즐겨찾기 플래그.',
    status: 'active',
  }),
  createdAt: Object.freeze({
    columnKey: 'createdAt',
    label: '등록일',
    category: 'core',
    domains: Object.freeze(['core']),
    sourceType: 'field',
    sourceFieldKey: 'customer.createdAt',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: true,
    description: '고객 레코드 생성 시각 컬럼.',
    status: 'active',
  }),
  assigneeUserId: Object.freeze({
    columnKey: 'assigneeUserId',
    label: '담당자',
    category: 'core',
    domains: Object.freeze(['core']),
    sourceType: 'field',
    sourceFieldKey: 'customer.assigneeUserId',
    valueType: 'number',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: false,
    description: '담당 사용자 id 표시 컬럼.',
    status: 'active',
  }),
  memoSummary: Object.freeze({
    columnKey: 'memoSummary',
    label: '메모 요약',
    category: 'document',
    domains: Object.freeze(['core']),
    sourceType: 'derived',
    sourceFieldKey: 'customer.memo',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: false,
    filterable: false,
    visibleDefault: true,
    description: '인라인/노트에서 요약 문자열 파생 표시.',
    status: 'active',
  }),
  lastConsultDate: Object.freeze({
    columnKey: 'lastConsultDate',
    label: '최근 상담일',
    category: 'core',
    domains: Object.freeze(['core']),
    sourceType: 'aggregate',
    featureDependency: 'crm-consultations',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: true,
    description: '상담 기능에서 집계한 최종 상담일.',
    status: 'active',
  }),
  ssnMasked: Object.freeze({
    columnKey: 'ssnMasked',
    label: '주민등록번호(표시)',
    category: 'personal',
    domains: Object.freeze(['insurance']),
    sourceType: 'derived',
    sourceFieldKey: 'insurance.ssn',
    valueType: 'string',
    privacyLevel: 'identifying',
    sortable: false,
    filterable: false,
    visibleDefault: true,
    description: 'SSN 마스킹 문자열 표시.',
    status: 'active',
  }),
  carNumber: Object.freeze({
    columnKey: 'carNumber',
    label: '차량번호',
    category: 'vehicle',
    domains: Object.freeze(['insurance']),
    sourceType: 'field',
    sourceFieldKey: 'vehicle.carNumber',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: false,
    filterable: true,
    visibleDefault: true,
    description: '대표 차량 번호판 표시 컬럼.',
    status: 'active',
  }),
  renewalDate: Object.freeze({
    columnKey: 'renewalDate',
    label: '만기일',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    sourceType: 'field',
    sourceFieldKey: 'insurance.renewalDate',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: true,
    description: '갱신·만기 예정일.',
    status: 'active',
  }),
  insuranceAge: Object.freeze({
    columnKey: 'insuranceAge',
    label: '보험나이',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    sourceType: 'field',
    sourceFieldKey: 'insurance.insuranceAge',
    valueType: 'number',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: false,
    description: '보험나이 표시 컬럼.',
    status: 'active',
  }),
  nextAgeDate: Object.freeze({
    columnKey: 'nextAgeDate',
    label: '상령일',
    category: 'insurance',
    domains: Object.freeze(['insurance']),
    sourceType: 'field',
    sourceFieldKey: 'insurance.nextAgeDate',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: false,
    description: '상령일 표시 컬럼.',
    status: 'active',
  }),
  businessName: Object.freeze({
    columnKey: 'businessName',
    label: '사업장명',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'business.name',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '사업장 상호.',
    status: 'active',
  }),
  businessNumber: Object.freeze({
    columnKey: 'businessNumber',
    label: '사업자등록번호',
    category: 'business',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'business.registrationNumber',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: false,
    description: '사업자번호.',
    status: 'active',
  }),
  applicationType: Object.freeze({
    columnKey: 'applicationType',
    label: '신청 유형',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'gov.applicationType',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '정부 지원 신청 유형.',
    status: 'active',
  }),
  productName: Object.freeze({
    columnKey: 'productName',
    label: '접수상품명',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'gov.productName',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '접수 상품.',
    status: 'active',
  }),
  programName: Object.freeze({
    columnKey: 'programName',
    label: '지원사업명',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'gov.programName',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: false,
    description: '지원 사업명.',
    status: 'active',
  }),
  govStatus: Object.freeze({
    columnKey: 'govStatus',
    label: '진행 상태',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'gov.status',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '지원 건 진행 단계.',
    status: 'active',
  }),
  supportAmount: Object.freeze({
    columnKey: 'supportAmount',
    label: '필요자금',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'gov.supportAmount',
    valueType: 'number',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: true,
    description: '필요·신청 금액.',
    status: 'active',
  }),
  paymentStatus: Object.freeze({
    columnKey: 'paymentStatus',
    label: '입금 상태',
    category: 'contract',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'contract.paymentStatus',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '수임료 입금 상태.',
    status: 'active',
  }),
  signatureStatus: Object.freeze({
    columnKey: 'signatureStatus',
    label: '전자서명 상태',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'document.signatureStatus',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '전자서명 진행.',
    status: 'active',
  }),
  submittedAt: Object.freeze({
    columnKey: 'submittedAt',
    label: '접수일',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'gov.submittedAt',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: false,
    description: '접수일.',
    status: 'active',
  }),
  dueDate: Object.freeze({
    columnKey: 'dueDate',
    label: '마감일',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'gov.dueDate',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: true,
    description: '제출/보완 마감.',
    status: 'active',
  }),
  assignee: Object.freeze({
    columnKey: 'assignee',
    label: '담당자',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'gov.assignee',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '건 담당자.',
    status: 'active',
  }),
  result: Object.freeze({
    columnKey: 'result',
    label: '결과',
    category: 'document',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'gov.result',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '지원 결과.',
    status: 'active',
  }),
  managementLastConsultDate: Object.freeze({
    columnKey: 'managementLastConsultDate',
    label: '최근 상담일',
    category: 'management',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'management.lastConsultDate',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: false,
    description: '관리용 최근 상담일 필드.',
    status: 'active',
  }),
  managementMemoSummary: Object.freeze({
    columnKey: 'managementMemoSummary',
    label: '메모 요약',
    category: 'management',
    domains: Object.freeze(['government', 'gov_support']),
    sourceType: 'field',
    sourceFieldKey: 'management.memoSummary',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: false,
    filterable: false,
    visibleDefault: false,
    description: '관리 메모 한 줄 요약.',
    status: 'active',
  }),
  membershipType: Object.freeze({
    columnKey: 'membershipType',
    label: '회원권 유형',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    sourceType: 'field',
    sourceFieldKey: 'gym.membershipType',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '헬스·PT 등 회원권 유형.',
    status: 'preview',
  }),
  /**
   * `programName`(columnKey SSOT): `gov.programName` 과 고정 매핑 — 변경 금지(정부 템플릿 등 소비처 유지).
   * 체육관은 다른 sourceField(`gym.programName`)를 쓰므로 **`gymProgramName`** 로 분리했다.
   */
  gymProgramName: Object.freeze({
    columnKey: 'gymProgramName',
    label: '프로그램명',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    sourceType: 'field',
    sourceFieldKey: 'gym.programName',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '등록 운동 프로그램·수업명.',
    status: 'preview',
  }),
  membershipEndDate: Object.freeze({
    columnKey: 'membershipEndDate',
    label: '회원권 만료일',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    sourceType: 'field',
    sourceFieldKey: 'gym.membershipEndDate',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: true,
    description: '회원권 만료일.',
    status: 'preview',
  }),
  remainingSessions: Object.freeze({
    columnKey: 'remainingSessions',
    label: '잔여 횟수',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    sourceType: 'field',
    sourceFieldKey: 'gym.remainingSessions',
    valueType: 'number',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: true,
    description: '이용 가능 잔여 세션 수.',
    status: 'preview',
  }),
  trainerName: Object.freeze({
    columnKey: 'trainerName',
    label: '담당 트레이너',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    sourceType: 'field',
    sourceFieldKey: 'gym.trainerName',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '담당 트레이너 이름.',
    status: 'preview',
  }),
  lastVisitDate: Object.freeze({
    columnKey: 'lastVisitDate',
    label: '마지막 방문일',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    sourceType: 'field',
    sourceFieldKey: 'gym.lastVisitDate',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: true,
    description: '최종 방문일.',
    status: 'preview',
  }),
  nextReservationDate: Object.freeze({
    columnKey: 'nextReservationDate',
    label: '다음 예약일',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    sourceType: 'field',
    sourceFieldKey: 'gym.nextReservationDate',
    valueType: 'date',
    privacyLevel: 'normal',
    sortable: true,
    filterable: false,
    visibleDefault: true,
    description: '다음 예약 일정.',
    status: 'preview',
  }),
  /**
   * `paymentStatus`(columnKey SSOT): 계약 입금 상태 `contract.paymentStatus` 에 고정 — 변경 금지.
   * 체육관 회비 상태는 다른 sourceField(`gym.paymentStatus`) 이므로 **`gymPaymentStatus`** 로 분리했다.
   */
  gymPaymentStatus: Object.freeze({
    columnKey: 'gymPaymentStatus',
    label: '결제 상태',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    sourceType: 'field',
    sourceFieldKey: 'gym.paymentStatus',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '회비·패키지 결제 상태.',
    status: 'preview',
  }),
  renewalStatus: Object.freeze({
    columnKey: 'renewalStatus',
    label: '재등록 상태',
    category: 'gym',
    domains: Object.freeze(['gym'] as const),
    sourceType: 'field',
    sourceFieldKey: 'gym.renewalStatus',
    valueType: 'string',
    privacyLevel: 'normal',
    sortable: true,
    filterable: true,
    visibleDefault: true,
    description: '재등록·연장 여부.',
    status: 'preview',
  }),
  // TODO(registry): domains 리터럴을 Entry 타입에 맞추면 `as unknown as` 제거 후보
}) as unknown as Readonly<Record<string, Readonly<ListColumnRegistryEntry>>>
