import type { CustomerIndustryTemplate } from '../customerTemplate.types'

/**
 * 주류회사 CRM 고객/거래처 템플릿 v1.
 * 스칼라 코어 필드 + liquor_customers* API 기반 구조화 탭.
 */
export const liquorCustomerTemplateV01: CustomerIndustryTemplate = {
  meta: {
    templateId: 'liquor_customer_v1',
    industryCode: 'liquor',
    version: '1.0.0',
    schemaVersion: 'customer-template.v1',
  },
  sharedFeatureBindings: Object.freeze([
    'crm-storage-files',
    'crm-consultations',
    'crm-inline-notes',
  ]),
  extensionFeatureBindings: Object.freeze([
    'liquor-customer-profile',
    'liquor-customer-contacts',
    'liquor-support-contracts',
    'liquor-repayments',
    'liquor-support-items',
    'liquor-customer-files',
    'liquor-customer-notes',
    'liquor-signatures-link',
  ]),
  formFields: Object.freeze([
    {
      fieldKey: 'customer.name',
      label: '거래처명',
      widget: 'text',
      required: true,
      visibleDefault: true,
      order: 100,
      privacyLevel: 'normal',
      domain: 'liquor',
      storage: 'core',
    },
    {
      fieldKey: 'customer.phone',
      label: '연락처',
      widget: 'phone',
      required: true,
      visibleDefault: true,
      order: 110,
      privacyLevel: 'normal',
      domain: 'liquor',
      storage: 'core',
    },
    {
      fieldKey: 'customer.address',
      label: '주소',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 120,
      privacyLevel: 'normal',
      domain: 'liquor',
      storage: 'core',
    },
    {
      fieldKey: 'liquor.partyType',
      label: '거래처 구분',
      widget: 'select',
      required: true,
      visibleDefault: true,
      order: 130,
      privacyLevel: 'normal',
      domain: 'liquor',
      storage: 'extension',
      options: Object.freeze([
        { value: 'individual', label: '개인' },
        { value: 'business', label: '사업장' },
      ]),
    },
    {
      fieldKey: 'liquor.accountStatus',
      label: '거래처 상태',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 140,
      privacyLevel: 'normal',
      domain: 'liquor',
      storage: 'extension',
      options: Object.freeze([
        { value: 'active', label: '거래중' },
        { value: 'paused', label: '거래중지' },
        { value: 'closed', label: '거래종료' },
      ]),
    },
  ]),
  listColumns: Object.freeze([
    {
      columnKey: 'customer_name',
      label: '거래처명',
      sourceFieldKey: 'customer.name',
      visibleDefault: true,
      order: 100,
      domain: 'liquor',
    },
    {
      columnKey: 'customer_phone',
      label: '연락처',
      sourceFieldKey: 'customer.phone',
      visibleDefault: true,
      order: 110,
      domain: 'liquor',
    },
    {
      columnKey: 'liquor_party_type',
      label: '구분',
      sourceFieldKey: 'liquor.partyType',
      visibleDefault: true,
      order: 120,
      domain: 'liquor',
      displayType: 'text',
    },
    {
      columnKey: 'liquor_account_status',
      label: '상태',
      sourceFieldKey: 'liquor.accountStatus',
      visibleDefault: true,
      order: 130,
      domain: 'liquor',
      displayType: 'text',
    },
  ]),
  detailTabs: Object.freeze([
    { tabId: 'liquor_basic', label: '기본정보', featureBinding: 'liquor-customer-profile', order: 100, visibleDefault: true, domain: 'liquor' },
    { tabId: 'liquor_contacts', label: '담당자', featureBinding: 'liquor-customer-contacts', order: 110, visibleDefault: true, domain: 'liquor' },
    { tabId: 'liquor_support', label: '지원/채권', featureBinding: 'liquor-support-contracts', order: 120, visibleDefault: true, domain: 'liquor' },
    { tabId: 'liquor_repayments', label: '상환내역', featureBinding: 'liquor-repayments', order: 130, visibleDefault: true, domain: 'liquor' },
    { tabId: 'liquor_items', label: '지원물품', featureBinding: 'liquor-support-items', order: 140, visibleDefault: true, domain: 'liquor' },
    { tabId: 'liquor_files', label: '첨부문서', featureBinding: 'liquor-customer-files', order: 150, visibleDefault: true, domain: 'liquor' },
    { tabId: 'liquor_notes', label: '메모/활동', featureBinding: 'liquor-customer-notes', order: 160, visibleDefault: true, domain: 'liquor' },
    { tabId: 'liquor_signatures', label: '전자서명', featureBinding: 'liquor-signatures-link', order: 170, visibleDefault: true, domain: 'liquor' },
  ]),
}
