import type { CustomerIndustryTemplate } from '../customerTemplate.types'

/**
 * 국가지원 사업 CRM 고객 템플릿 v0.1 — canonical fieldKey.
 * 코어 컬럼은 customers 테이블, 그 외는 `crm_extension.fields`에 저장된다.
 *
 * formFields 순서 = 기본고객 → 사업장 → 지원사업 → 기대출 → 계약 → 문서 → 내부관리(담당·유입·우선·상담·메모요약).
 * detailTabs: 기본(customer) → 사업장(business) → 지원/접수(gov) → 대출+계약(loan+contract) → 서류+내부관리(document+management).
 * 각 탭에 fieldKeys 가 있어야 공통 상세 렌더러가 읽기 전용 행을 그린다.
 */
export const governmentCustomerTemplateV01: CustomerIndustryTemplate = {
  meta: {
    templateId: 'government_customer_v1',
    industryCode: 'government',
    version: '0.1.0',
    schemaVersion: 'customer-template.v1',
  },
  sharedFeatureBindings: Object.freeze([
    'crm-storage-files',
    'crm-consultations',
    'crm-inline-notes',
    'documents-send',
    'notifications-sms-gateway',
    'permissions-scope',
  ]),
  extensionFeatureBindings: Object.freeze([
    'gov-application-workflow',
    'gov-document-checklist',
    'gov-status-tracking',
    'gov-deadline-alert',
    'gov-agency-routing',
    'gov-supplement-request',
    'gov-result-management',
  ]),
  formFields: Object.freeze([
    // A. 기본 고객 정보
    {
      fieldKey: 'customer.name',
      label: '성함',
      widget: 'text',
      required: true,
      visibleDefault: true,
      order: 100,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'customer.phone',
      label: '연락처',
      widget: 'phone',
      required: true,
      visibleDefault: true,
      order: 110,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'customer.carrier',
      label: '통신사',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 120,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'customer.ssn',
      label: '주민번호',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 130,
      privacyLevel: 'identifying',
      domain: 'government',
    },
    {
      fieldKey: 'customer.address',
      label: '자택주소',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 140,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'customer.homeType',
      label: '자택형태',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 150,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'customer.creditScoreKcb',
      label: '신용점수 KCB',
      widget: 'number',
      required: false,
      visibleDefault: true,
      order: 160,
      privacyLevel: 'sensitive',
      domain: 'government',
    },
    {
      fieldKey: 'customer.creditScoreNice',
      label: '신용점수 NICE',
      widget: 'number',
      required: false,
      visibleDefault: true,
      order: 170,
      privacyLevel: 'sensitive',
      domain: 'government',
    },
    {
      fieldKey: 'customer.memo',
      label: '특이사항',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 180,
      privacyLevel: 'normal',
      domain: 'government',
    },
    // B. 사업장 정보
    {
      fieldKey: 'business.name',
      label: '사업장명칭',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 200,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'business.ownerName',
      label: '대표자명',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 210,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'business.openedAt',
      label: '개업년월일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 220,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'business.registrationNumber',
      label: '사업자등록번호',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 230,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'business.address',
      label: '사업장 소재지',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 240,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'business.category',
      label: '사업자 종목',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 250,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'business.type',
      label: '업태',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 260,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'business.placeType',
      label: '사업장 형태',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 270,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'business.phone',
      label: '사업장 번호',
      widget: 'phone',
      required: false,
      visibleDefault: true,
      order: 280,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'business.vatReported',
      label: '부가세 신고 유/무',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 290,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'business.incomeProofAvailable',
      label: '소득금액증명원 발급 여부',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 300,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'business.annualIncome',
      label: '연소득',
      widget: 'number',
      required: false,
      visibleDefault: true,
      order: 310,
      privacyLevel: 'sensitive',
      domain: 'government',
    },
    {
      fieldKey: 'business.taxArrears',
      label: '세금 체납 여부',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 320,
      privacyLevel: 'normal',
      domain: 'government',
    },
    // C. 지원사업 신청
    {
      fieldKey: 'gov.productName',
      label: '접수상품명',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 400,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.applicationType',
      label: '신청 유형',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 410,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.caseNumber',
      label: '접수번호',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 420,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.programName',
      label: '지원사업명',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 430,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.agency',
      label: '관할 기관',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 440,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.department',
      label: '담당 부서',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 450,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.status',
      label: '진행 상태',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 460,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.submittedAt',
      label: '접수일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 470,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.dueDate',
      label: '마감일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 480,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.assignee',
      label: '담당자',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 490,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.requiredDocuments',
      label: '필요 서류',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 500,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.supportAmount',
      label: '필요자금',
      widget: 'number',
      required: false,
      visibleDefault: true,
      order: 510,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.approvalAmount',
      label: '승인금액',
      widget: 'number',
      required: false,
      visibleDefault: true,
      order: 520,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.result',
      label: '결과',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 530,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.rejectionReason',
      label: '반려 사유',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 540,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'gov.supplementRequest',
      label: '보완 요청 내용',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 550,
      privacyLevel: 'normal',
      domain: 'government',
    },
    // D. 기대출
    {
      fieldKey: 'loan.existingLoans',
      label: '기대출',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 600,
      privacyLevel: 'normal',
      domain: 'government',
    },
    // E. 계약/수임/인증서
    {
      fieldKey: 'contract.totalFee',
      label: '수임료 총액',
      widget: 'number',
      required: false,
      visibleDefault: true,
      order: 700,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'contract.depositAmount',
      label: '계약금',
      widget: 'number',
      required: false,
      visibleDefault: true,
      order: 710,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'contract.balanceAmount',
      label: '잔금',
      widget: 'number',
      required: false,
      visibleDefault: true,
      order: 720,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'contract.paymentStatus',
      label: '입금 상태',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 730,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'contract.paymentDueDate',
      label: '입금 예정일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 735,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'contract.certificateDelegated',
      label: '인증서 위임 여부',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 740,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'contract.certificateType',
      label: '인증서 종류',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 750,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'contract.status',
      label: '계약 상태',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 760,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'contract.paymentMemo',
      label: '수임료/입금 메모',
      widget: 'textarea',
      required: false,
      visibleDefault: true,
      order: 770,
      privacyLevel: 'normal',
      domain: 'government',
    },
    // F. 문서/전자서명
    {
      fieldKey: 'document.signatureStatus',
      label: '전자서명 상태',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 800,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'document.lastSentAt',
      label: '최근 문서 발송일',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 810,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'document.lastCompletedAt',
      label: '최근 문서 완료일',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 820,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'document.hasLegalEvidence',
      label: '법적 로그 여부',
      widget: 'boolean',
      required: false,
      visibleDefault: true,
      order: 830,
      privacyLevel: 'normal',
      domain: 'government',
    },
    // G. 내부 관리 (담당·운영 → 일정·요약 순; preview 표는 order 정렬)
    {
      fieldKey: 'management.ownerUserId',
      label: '담당 영업사원',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 850,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'management.source',
      label: '유입 경로',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 860,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'management.priority',
      label: '우선순위',
      widget: 'select',
      required: false,
      visibleDefault: true,
      order: 870,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'management.lastConsultDate',
      label: '최근 상담일',
      widget: 'date',
      required: false,
      visibleDefault: true,
      order: 880,
      privacyLevel: 'normal',
      domain: 'government',
    },
    {
      fieldKey: 'management.memoSummary',
      label: '메모 요약',
      widget: 'text',
      required: false,
      visibleDefault: true,
      order: 890,
      privacyLevel: 'normal',
      domain: 'government',
    },
  ]),
  listColumns: Object.freeze([
    {
      columnKey: 'name',
      label: '성함',
      order: 10,
      visibleDefault: true,
      domain: 'government',
    },
    {
      columnKey: 'phone',
      label: '연락처',
      order: 20,
      visibleDefault: true,
      domain: 'government',
    },
    {
      columnKey: 'businessName',
      label: '사업장명',
      order: 30,
      visibleDefault: true,
      domain: 'government',
    },
    {
      columnKey: 'applicationType',
      label: '신청 유형',
      order: 40,
      visibleDefault: true,
      domain: 'government',
    },
    {
      columnKey: 'productName',
      label: '접수상품명',
      order: 50,
      visibleDefault: true,
      domain: 'government',
    },
    {
      columnKey: 'govStatus',
      label: '진행 상태',
      order: 60,
      visibleDefault: true,
      domain: 'government',
    },
    {
      columnKey: 'supportAmount',
      label: '필요자금',
      order: 70,
      visibleDefault: true,
      domain: 'government',
    },
    {
      columnKey: 'paymentStatus',
      label: '입금 상태',
      order: 80,
      visibleDefault: true,
      domain: 'government',
    },
    {
      columnKey: 'signatureStatus',
      label: '전자서명 상태',
      order: 90,
      visibleDefault: true,
      domain: 'government',
    },
    {
      columnKey: 'dueDate',
      label: '마감일',
      order: 100,
      visibleDefault: true,
      domain: 'government',
    },
    {
      columnKey: 'assignee',
      label: '담당자',
      order: 110,
      visibleDefault: true,
      domain: 'government',
    },
    // TODO: 좁은 리스트 폭에서 열 과다 시 이 컬럼부터 visibleDefault: false 후보로 내릴 수 있음(v0.1은 기본 노출 유지).
    {
      columnKey: 'result',
      label: '결과',
      order: 120,
      visibleDefault: true,
      domain: 'government',
    },
    {
      columnKey: 'businessNumber',
      label: '사업자등록번호',
      order: 130,
      visibleDefault: false,
      domain: 'government',
    },
    {
      columnKey: 'programName',
      label: '지원사업명',
      order: 140,
      visibleDefault: false,
      domain: 'government',
    },
    {
      columnKey: 'submittedAt',
      label: '접수일',
      order: 150,
      visibleDefault: false,
      domain: 'government',
    },
    {
      columnKey: 'managementLastConsultDate',
      label: '최근 상담일',
      order: 160,
      visibleDefault: false,
      domain: 'government',
    },
    {
      columnKey: 'managementMemoSummary',
      label: '메모 요약',
      order: 170,
      visibleDefault: false,
      domain: 'government',
    },
  ]),
  detailTabs: Object.freeze([
    {
      tabId: 'gov-customer',
      label: '기본 정보',
      featureBinding: 'gov-section-customer',
      order: 10,
      domain: 'government',
      visibleDefault: true,
      fieldKeys: Object.freeze([
        'customer.name',
        'customer.phone',
        'customer.carrier',
        'customer.ssn',
        'customer.address',
        'customer.homeType',
        'customer.creditScoreKcb',
        'customer.creditScoreNice',
        'customer.memo',
      ]),
    },
    {
      tabId: 'gov-business',
      label: '사업자 정보',
      featureBinding: 'gov-section-business',
      order: 20,
      domain: 'government',
      visibleDefault: true,
      fieldKeys: Object.freeze([
        'business.name',
        'business.ownerName',
        'business.openedAt',
        'business.registrationNumber',
        'business.address',
        'business.category',
        'business.type',
        'business.placeType',
        'business.phone',
        'business.vatReported',
        'business.incomeProofAvailable',
        'business.annualIncome',
        'business.taxArrears',
      ]),
    },
    {
      tabId: 'gov-program',
      label: '지원·접수 정보',
      featureBinding: 'gov-application-workflow',
      order: 30,
      domain: 'government',
      visibleDefault: true,
      fieldKeys: Object.freeze([
        'gov.productName',
        'gov.applicationType',
        'gov.caseNumber',
        'gov.programName',
        'gov.agency',
        'gov.department',
        'gov.status',
        'gov.submittedAt',
        'gov.dueDate',
        'gov.assignee',
        'gov.requiredDocuments',
        'gov.supportAmount',
        'gov.approvalAmount',
        'gov.result',
        'gov.rejectionReason',
        'gov.supplementRequest',
      ]),
    },
    {
      tabId: 'gov-loans',
      label: '대출·계약 정보',
      featureBinding: 'gov-section-loans',
      order: 40,
      domain: 'government',
      visibleDefault: true,
      fieldKeys: Object.freeze([
        'loan.existingLoans',
        'contract.totalFee',
        'contract.depositAmount',
        'contract.balanceAmount',
        'contract.paymentStatus',
        'contract.paymentDueDate',
        'contract.certificateDelegated',
        'contract.certificateType',
        'contract.status',
        'contract.paymentMemo',
      ]),
    },
    {
      tabId: 'gov-documents',
      label: '서류·내부 관리',
      featureBinding: 'gov-section-documents',
      order: 50,
      domain: 'government',
      visibleDefault: true,
      fieldKeys: Object.freeze([
        'document.signatureStatus',
        'document.lastSentAt',
        'document.lastCompletedAt',
        'document.hasLegalEvidence',
        'management.ownerUserId',
        'management.source',
        'management.priority',
        'management.lastConsultDate',
        'management.memoSummary',
      ]),
    },
  ]),
}
